aws-controllers-k8s/community

.gitignore
README.md
docs/README.md
docs/background.md

Background

---

README.md
docs/background.md

- adds Slack and mailing list info
- expands on motivation and background

Project infra and background

---

.github/PULL_REQUEST_TEMPLATE.md

*Issue #, if available:*
N/A
*Description of changes:*
Update Pull Request template to reference appropriate license. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

updates pull request template

---

cmd/ack-generate/command/types.go
pkg/model/enum_def.go
pkg/schema/crd_test.go
pkg/schema/enum_def.go
pkg/schema/enum_def_test.go
pkg/schema/type_def.go
pkg/schema/util.go
pkg/template/enums.go
pkg/testutil/schema_helper.go
templates/enums.go.tpl

Discovered an issue in outputting integer-based enum definitions while
writing the unit tests here. That issue (conversion from float64 to
string representation of the integer values) has been corrected in this
patch.

add unit tests for enum definitions

---

pkg/types/aws_resource_manager.go
services/example/pkg/resource/book.go
services/example/pkg/resource/book_resource_manager.go

Adds simple implementations of the Create, Update and Delete methods of
the example book resource manager.

CUD implementation for bookstore example res mgr

---

.circleci/config.yml

* Doing a small refactoring as part of comments on pull#53
* Updating the job-names from 'build'->'unit_tests' & 'integration_test' -> 'integration_tests'

Circleci setup refactoring

---

cmd/ack-generate/command/controller.go
pkg/template/controller_dockerfile.go
templates/Dockerfile.tpl
templates/boilerplate_hash.go.tpl

generate Dockerfile on "ack generate controller servicealias"

ack generate controller Dockerfile

---

cmd/ack-generate/command/controller.go
pkg/runtime/config.go
pkg/template/controller_dockerfile.go
services/bookstore/cmd/controller/main.go
services/petstore/cmd/controller/main.go
templates/cmd/controller/main.go.tpl

Setting Logger with configurable debug option

---

scripts/build-controller.sh

Generating CRDs from build-controller.sh

---

pkg/model/crd_test.go

Couple tiny things I missed in an earlier commit...

Quick fixes for crd unit tests

---

pkg/model/helper.go

Issue: #143  
Description of changes: Updated the helper method to exclude the ignored resources

fix: Ignored resource names appear in import for main.go causing docker image build failure

---

docs/contents/dev-docs/code-generation.md
docs/contents/dev-docs/overview.md
docs/contents/dev-docs/setup.md
docs/contents/dev-docs/testing.md
docs/mkdocs.yml

Couple of polishing in the dev docs and make it more inclusive (contributors rather than developers).

updates contributor docs

---

.github/workflows/on.pull-request.main.yaml

Adds a super-simple workflow with a single `make test` step for pull
requests to `main` branch.
Issue #6 

add Github Actions workflow for make test

---

.github/workflows/on.pull-request.main.yaml

Adding checkout step to fix the CI error appearing in #150: https://github.com/aws/aws-controllers-k8s/runs/955700618

add checkout step to actions pipeline

---

.github/workflows/on.pull-request.main.yaml
Makefile
pkg/model/crd.go
pkg/model/crd_test.go
scripts/install_mockery.sh

Adds nil guards to the code generated that constructs or sets Status
fields from Output shape contents.
Issue #127 

nil guards for Status from output shape

---

templates/pkg/crd_sdk.go.tpl

Late night coding, I missed git adding the changes to
templates/pkg/crd_sdk.go.tpl to the last commit.

Missed adding template changes

---

docs/contents/dev-docs/testing.md
docs/mkdocs.yml

Added docs to create a role which should have a trust relationship required to assume the role. 

update dev docs to include ROLE ARN setup

---

CONTRIBUTING.md
README.md
docs/contents/index.md
docs/contents/services.md
docs/mkdocs.yml
services/readme.md

* Significant expansion of readme for both the main project and github pages site
* Added a list of supported services (/services/services.md) to track service support status, give helm chart value, and link to AWS documentation.

Preview readme and website updates

---

scripts/kind-build-test.sh

The MissingRegion error we were seeing in test runs was actually due to
the AWS_ROLE_ARN environment variable not being set. This was due to me
running `./scripts/kind-build-test.sh -p -s ecr -r "$ROLE_ARN"` in a
terminal where I had not source/exported my IAM Role used for testing.
This resulted in the ECR service controller starting up, but a ""-valued
AWS_ROLE_ARN environment variable being placed into the Deployment env.
It was this that was "missing a region"... :(
This PR makes the `-r $ROLE_ARN` a required flag for
`scripts/kind-build-test.sh` to avoid problems like this in the future.

ensure scripts/kind-build-test.sh has AWS Role ARN

---

docs/contents/dev-docs/testing.md

Description of changes: updated testing docs

minor update testing docs

---

scripts/kind-build-test.sh

Description of changes: Fixing kind build script if no ROLE_ARN is passed

fixing kind-build-test script when no ROLE_ARN is passed

---

docs/contents/dev-docs/testing.md

Description of changes: testing documentation updated

update testing docs

---

docs/contents/dev-docs/testing.md

Description of changes: Updated testing docs.

Updated testing docs

---

docs/contents/dev-docs/testing.md

For the dev preview, make all steps explicit and ask for feedback

improves testing instructions for dev preview

---

docs/contents/dev-docs/testing.md

sync up docs with #201

---

docs/contents/dev-docs/testing.md

Fix ARN role for test docs

---

services/elasticache/generator.yaml
test/e2e/elasticache/cache_subnet_group/smoke.sh
test/e2e/elasticache/smoke_cache_subnet_group.sh

Issue #215 
Description of changes: generator config and smoke test for ElastiCache CacheSubnetGroup 

generator config and smoke test for ElastiCache CacheSubnetGroup #215

---

README.md

Issue #, if available: https://github.com/aws/aws-controllers-k8s/issues/177 
Add initial set of badges, including:
- contributions welcome
- still in preview status
- open issues
- license
- go.mod version
- go report
- github watchers/stars/forks
Happy to add any additional ones.

Add initial set of badges

---

docs/contents/community/faq.md

fixes #223 
Add two additional FAQ questions/answers.

Add FAQ for cluster-api and cdk8s

---

pkg/runtime/registry.go

Correct typo

---

docs/contents/dev-docs/testing.md
docs/contents/services.md

Adds the required doc updates to get SNS into developer preview.
Issue #202 

doc updates to get SNS into dev preview

---

docs/contents/dev-docs/testing.md

improves dev preview docs concerning `controller-gen`

---

docs/design/proposals/carm/cross-account-resource-management.md

Issue #, if available: #102 
Follow up to PR #62. Updating the CARM design document according the latest [review](https://github.com/aws/aws-controllers-k8s/pull/62#pullrequestreview-448935019):
- Clarifying that namespace annotations are not necessary but they can be used to override the AWS Account ID in which resource will be created.
- Adding more details on how ACK controllers will access `ack-carm-config-map` ConfigMap key values.
- Adding code snippets for the AWS Client pivot and auditability of the AWS Account RoleARN
- Small change to the "ack-carm-config-map" `.data.accounts` structure

Enhance cross resource account management design document

---

services/elasticache/pkg/resource/replication_group/custom_set_output.go
services/elasticache/pkg/resource/replication_group/custom_update_api.go
services/elasticache/pkg/resource/replication_group/custom_update_api_test.go

Issue #210 
Implementation for modify replication group shard configuration and replica count

update replication group - modify shard configuration and replica count

---

docs/contents/dev-docs/testing.md
services/apigatewayv2/config/iam/recommended-policy-arn

* Adding Amazon API Gateway V2 service in testing.md
* Adding recommended-policy-arn for APIGatewayV2 service.

Doc updates for apigatewayv2 service.

---

.github/workflows/on.pull-request.main.yaml

Issue #, if available: #327 
Description of changes: 
- Included kind cluster deletion
- Added mockery installation for self-hosted runners
PR closes #327 

Delete kind clusters during e2e tests

---

.github/workflows/cleanup-self-hosted.yml

wish there was a way to test stuff without merging...

remove leading dot in github action workflow var

---

.github/workflows/cleanup-self-hosted.yml

investigating YAML failures

---

scripts/install-kind.sh

forgot to include common.sh

---

.github/workflows/cleanup-self-hosted.yml

https://github.community/t/can-i-create-a-workflow-which-runs-on-all-of-by-self-hosted-runners/18478

Trick GH into running on all self-hosted runners

---

.github/workflows/cleanup-self-hosted.yml

misspelled hostnamectl

---

.github/workflows/e2e-test.yaml

inject SERVICE envvar from matrix

---

.github/workflows/e2e-test.yaml
scripts/lib/aws.sh

- Added the ARN role as a GitHub secret
- Enabled parallel execution
- Removed print statement with role ARN

Enabled parallel execution and used secrets

---

scripts/lib/aws_elasticache_testutil.sh
services/elasticache/pkg/resource/replication_group/custom_update_api.go
test/e2e/elasticache/cache_subnet_group/smoke.sh
test/e2e/elasticache/replication_group/e2e.sh

Issue #380 
* e2e tests for replication group and subnet group
* update in replication group custom update code to handle missing configuration scenario for decrease node groups

ElastiCache e2e tests for replication group, subnet group

---

test/e2e/s3/cross-account.sh

Issue #368 and follow-up to https://github.com/aws/aws-controllers-k8s/pull/354#discussion_r498401505
- Create testing namespace and ack-role-account-map ConfigMap before running CARM smoke tests

Create testing namespace and ack-role-account-map ConfigMap before running CARM smoke tests

---

.github/workflows/e2e-test.yaml

Added labels for runners

---

.github/workflows/build-unit-test.yaml

try diff way of install c-g

---

.github/workflows/build-unit-test.yaml

remove sudo from install c-g

---

.github/workflows/build-unit-test.yaml

Try using setup-go GH action

---

.github/workflows/build-unit-test.yaml

Try installing c-g instead of c-t

---

.github/workflows/build-unit-test.yaml

Actually install c-g (don't use the -d flag in go get)

---

services/elasticache/pkg/resource/replication_group/custom_update_api.go
services/elasticache/pkg/resource/replication_group/custom_update_api_test.go

1. Updated logic to handle order of operations when
failover, multi az are present in desired Spec
2. Updated logic for Increase, Decrease replicas
payload to include only those Node Groups
from desired Spec that have matching nodeGroupId
present on server
Issue #413 

replication group custom modify logic fixes

---

docs/contents/services.md

add iam to roadmap

---

pkg/generate/template.go
templates/helm/templates/service-account.yaml

Issue N/A
- Create service account if `serviceAccount.create` is `true`

Create service account if `serviceAccount.create` is `true`

---

docs/contents/community/background.md

Description of changes: The existing link points to v0.5 which is a very old release. This PR updates it to provider-aws repo to be on the safe side regarding new releases.

Update link to Crossplane in RelatedProjects

---

README.md
docs/contents/community/discussions.md
docs/contents/index.md

Issue #, if available: #517 
Description of changes: Remove mailing list from README

Remove mailing list link from README

---

GOVERNANCE.md

Fix typo in `GOVERNANCE.md`:
accepeted -> accepted

Fix typo in `GOVERNANCE.md`

---

services/elasticache/pkg/resource/replication_group/custom_update_api.go
services/elasticache/pkg/resource/replication_group/custom_update_api_test.go

Issue #529 
- Added code to check node groups state before invoking modify replication group
- Updated unit tests to include corresponding test scenarios
```make test``` passed.

Defer modify replication group if any of its node groups is not in available state

---

docs/contents/user-docs/authorization.md

Issue #458 
- Add cross account resource management documentation

Document cross account resource management

---

scripts/delete-kind-cluster.sh

No issue but requested in #533 
I simply deleted any lines mentioning OVERRIDE_PATH.

Removing all lines in delete-kind-cluster containing OVERRIDE_PATH

---

scripts/kind-build-test.sh

Refactoring stage: Argument variable values as env variables instead of getopts strategy
Script: kind-build-test.sh
- Replaced getopts strategy with a fixed number of arguments (aws service name ) and env variable.
- Note that AWS_ROLE_ARN is defined as a variable during script startup:
`AWS_ROLE_ARN=${AWS_ROLE_ARN:-""}`
The above will cause the script to not fail even when the environment variable (previously passed as script argument) is not explicitly defined. I assumed this is intentional.

removed getopts strategy from kind-build-test.sh

---

templates/helm/templates/deployment.yaml
templates/helm/templates/service-account.yaml

Issue #562 
* Controller helm chart deployment template reads value for aws region
* Controller helm chart service account template reads value for the annotations

helm template updates for service account and deployment

---

services/elasticache/pkg/resource/cache_parameter_group/custom_api.go
services/elasticache/pkg/resource/cache_subnet_group/custom_set_output.go
services/elasticache/pkg/resource/replication_group/custom_set_output.go
services/elasticache/pkg/resource/replication_group/custom_update_api.go

* Updated ElastiCache controller custom logic to record api call metrics

record api call metrics for ElastiCache custom controller logic

---

services/elasticache/generator.yaml
services/elasticache/pkg/resource/cache_parameter_group/sdk.go
services/elasticache/pkg/resource/cache_subnet_group/sdk.go
services/elasticache/pkg/resource/replication_group/custom_update_api.go
services/elasticache/pkg/resource/replication_group/sdk.go
services/elasticache/pkg/resource/snapshot/sdk.go
templates/pkg/resource/sdk.go.tpl

* Updates to ElastiCache generator config for terminal codes for custom resources
* Updated template file to put each terminal code in new line for better formatting
* Regenerated ElastiCache ACK controller code

Update terminal codes for ElastiCache generator config

---

docs/contents/user-docs/irsa.md

Updated irsa.md file with steps to setup IRSA for ACK controller on EKS.

irsa setup details for ACK controller setup on EKS

---

Makefile

Issue #504
Fixed references to programs in ./scripts/* removing argument flags.

fix scripts reference

---

services/elasticache/generator.yaml

Issue N/A
- Fix elasticache generator config for CacheSubnetGroup.Events

Fix elasticache generator config for CacheSubnetGroup.Events

---

pkg/model/crd.go

Splits out the large `CRD.goCodeSetOutputForContainer()` method into
three separate methods, one for processing struct source types, one for
slice types and one for map types.
Same for the corresponding goCodeSetInputForContainer.

refactor: simplify goCodeSetOutputForContainer

---

docs/contents/dev-docs/testing.md

Fix minor typos on install-mockery.sh command

Update dev docs

---

pkg/generate/ack/apis.go
pkg/generate/config/resource.go
pkg/model/crd.go
templates/apis/crd.go.tpl

Issue N/A
- Generate CRD shortnames using resource generator configuration

Resource configuration to generate CRD shortnames/aliases

---

pkg/generate/code/check.go
pkg/generate/code/set_resource.go
pkg/generate/code/set_resource_test.go
pkg/generate/code/set_sdk.go
pkg/generate/crossplane/crossplane.go
templates/crossplane/README.md
templates/crossplane/boilerplate.go.tpl
templates/crossplane/pkg/controller.go.tpl
templates/crossplane/pkg/conversions.go.tpl
templates/crossplane/pkg/sdk_find_get_attributes.go.tpl
templates/pkg/resource/sdk_find_get_attributes.go.tpl

Description of changes: Adds support for attribute-based APIs such as SNS to Crossplane pipeline. All ACK tests pass, there is no change in output of ACK pipeline.
/cc @jaypipes 

crossplane: add support for attribute-based APIs

---

templates/crossplane/pkg/controller.go.tpl

Description of changes: There are cases where isUpToDate might make an API call which can result in error, so developers should be able to return that error.
Fixes https://github.com/crossplane/provider-aws/issues/501

Update crossplane controller template

---

scripts/BASH_STYLE_CONVENTIONS.md

Refactoring stage: Add Bash Style Conventions document.
Adding a style guide document to outline some of the adopted conventions when writing bash scripts for this repository. 
**Note**: This is intended to be just a kick off guide and it's expected to grow over the time. 

Bash conventions - first commit

---

docs/contents/services.md

Added / fixed in-page links. Removed duplicate EFS entry. Added links to relevant issue on GitHub.

docs: cleaned up services page

---

scripts/lib/aws/elasticache.sh

Looking at e2e test run failure logs for ElastiCache controller: https://github.com/aws-controllers-k8s/community/runs/1956783005?check_suite_focus=true
There seems need to enhance failure logs.
* Enhanced diagnostic logs for ElastiCache tests and fix for test methods.

Enhanced diagnostic logs for ElastiCache tests and fixes

---

docs/contents/services.md

Description of changes: Rendering of the services table was broken. This PR fixes it.

fix(docs): Fix table of services

---

test/e2e/sagemaker/resources/xgboost_transformjob.yaml
test/e2e/sagemaker/service_bootstrap.py
test/e2e/sagemaker/tests/test_transformjob.py

Integration tests for Transform Job in SageMaker - https://github.com/aws-controllers-k8s/sagemaker-controller/pull/4
Tests: create, read, update, delete
Using local kind cluster and pytest
Minor bug fix: Fixed a race condition between role creation and usage by switching the role creation and data copy operations. By the time data is copied, role is created and available to use by the integration test.

Integration tests for SageMaker Transform Job

---

test/e2e/sagemaker/resources/xgboost_hpojob.yaml
test/e2e/sagemaker/tests/test_hpo.py

Integration tests for HyperParameterTuning Job in SageMaker 
Related CR:  https://github.com/aws-controllers-k8s/sagemaker-controller/pull/5
Using local kind cluster and pytest

Integration tests for HyperParameterJob

---

scripts/kind-build-test.sh

Issue #, if available: None
Ensures the common bases are applied to test cluster (support for AdoptedResource currently)

Apply common manifest to test cluster

---

README.md

Issue N/a
- Add ACK community meeting details

Add ACK community meeting details

---

docs/contents/dev-docs/release.md

Updating the release process doc with latest prowjob approach.

Updating the release process doc with latest prowjob approach.

---

docs/contents/services.md
scripts/lib/aws.sh

Update website with SageMaker release status

doc update for SageMaker preview

---

docs/contents/services.md
scripts/lib/aws.sh

Update website with Application Auto Scaling release status

doc update for Application Auto Scaling Preview

---

docs/contents/user-docs/authorization.md

Fixes broken links in source code examples and documentation for
cross-account resource management.
Issue #120
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

[docs] fix CARM broken links

---

docs/content/docs/tutorials/sagemaker-example.md
docs/content/docs/user-docs/authorization.md
docs/content/docs/user-docs/cleanup.md
docs/content/docs/user-docs/install.md
docs/content/docs/user-docs/irsa.md

Fixed relative links and title capitalization for the SageMaker tutorial.

Fix relative links and title capitalization

---

docs/package-lock.json
docs/package.json

Issue #, if available: https://github.com/aws-controllers-k8s/community/security/dependabot/docs/package-lock.json/set-value/open
* Updated the dependencies in `package.json`
* ran `npm install` to update `package-lock.json`

dependency upgrade for `set-value` library

---

docs/content/docs/tutorials/sagemaker-example.md
docs/content/docs/user-docs/install.md
docs/content/docs/user-docs/irsa.md

Description of changes: I added a note about the Helm version specifications and made a small fix in the S3 bucket creation script. 
Also added the same Helm version note to installation page and fixed a broken link. 

Added Helm version note to SM Tutorial

---

docs/config/_default/menus.toml
docs/content/docs/community/overview.md
docs/content/docs/user-docs/authorization.md
docs/content/docs/user-docs/cleanup.md
docs/content/docs/user-docs/cross-account-resource-management.md
docs/content/docs/user-docs/install.md
docs/content/docs/user-docs/irsa.md
docs/content/docs/user-docs/multi-region-resource-management.md
docs/content/docs/user-docs/resource-crud.md

Issue: https://github.com/aws-controllers-k8s/community/issues/996
New Order
* INTRODUCTION
* Overview
* How it Works
* Services
* Release Phases
* GETTING STARTED
* Install ACK Controller
* Configure IAM Permissions
* Create AWS Resource
* Manage Resources In Multiple Region
* Manage Resources In Multiple AWS Accounts (CARM)
* Permissions Overview
* Uninstall ACK Controller
* TUTORIALS
* Machine Learning with the ACK SageMaker Controller
* CONTRIBUTOR DOCS
* Contribution Overview
* Code Generation
* API Inference
* Setup
* Building a Controller
* Testing
* Release
* DISCUSSION
* Background
* FAQ
* Discussions
I validated the new installation, IRSA and resource-creation commands by locally installing a s3 controller by following this guide.
By submitting this pull …

Reorder installation instructions with bucket creation and  update IRSA

---

docs/content/docs/community/services.md

Update ElasticsearchService controller to RELEASED/PREVIEW

---

docs/content/docs/user-docs/cross-account-resource-management.md
docs/content/docs/user-docs/install.md
docs/content/docs/user-docs/openshift.md

Version 2 attempt, previous closed PR is #1058
Closes #1039 
Simplified and aggregated OpenShift-specific stuff into one central document. This seems to flow much better without disrupting any of the existing documentation.

Adding initial OpenShift documentation (v2)

---

docs/content/docs/community/services.md

Congrats to the SageMaker team! :)

:tada: SageMaker to GA maintenance phase

---

docs/content/docs/community/services.md

Great work on this controller, @RedbackThomson!

:tada: EKS controller into Preview

---

ATTRIBUTION.md
CONTRIBUTING.md
docs/content/docs/contributor-docs/api-inference.md
docs/content/docs/contributor-docs/code-generation.md
docs/content/docs/contributor-docs/testing.md

Fix some broken links

---

docs/content/docs/tutorials/sagemaker-example.md

Readme changes for SageMaker Studio

Readme changes for SageMaker Studio

---

docs/design/proposals/resource-reference/cross-api-group.md
docs/design/proposals/resource-reference/resource-reference.md

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1091
* Proposal for supporting resource references from other service controllers i.e. different api-groups
See the rendered doc [here](https://github.com/vijtrip2/community/blob/xapigroup/docs/design/proposals/resource-reference/cross-api-group.md) 

proposal for referencing resource from another service controller

---

docs/content/docs/tutorials/rds-example.md

Update RDS tutorial to use Helm chart v0.0.17, which is the latest version of the Helm chart available.

Update RDS tutorial to use Helm chart v0.0.17

---

docs/design/proposals/native-binding/native-binding.md

Issue #, if available: #740
Adds a proposal for ACK-K8s native binding, allowing for K8s applications to bind to ACK resource fields.

K8s native binding design proposal

---

docs/content/docs/tutorials/rds-example.md
docs/content/docs/user-docs/authorization.md
docs/content/docs/user-docs/field-export.md

Adds a user guide describing the context, use case and example for `FieldExport`. 

Add documentation for `FieldExport`

---

docs/content/docs/tutorials/apigatewayv2-reference-example.md

Issue #1207 
* tutorial for APIGWv2 HTTP API using resource references

tutorial for APIGWv2 HTTP API using resource references

---

docs/requirements.txt

Fixes the conflicting Python requirements in the docs

Fix docs Python requirement conflict

---

docs/content/docs/contributor-docs/release.md

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1072
* Expand the stable release process
* Add step to include helm chart version update for stable release. Similar [commit](https://github.com/aws-controllers-k8s/sagemaker-controller/commit/1bb06ea829763d6d3b52e9c5e351ceb2be878800) was needed for Sagemaker controller.

update stable release to include helm version update

---

docs/content/docs/tutorials/memorydb-example.md

* Rearranged content
* Updated example Pod spec to use `public.ecr.aws/sam/build-python3.8:latest` image
* Added verification steps

Update memorydb tutorial example pod and verification steps

---

docs/content/docs/tutorials/rds-example.md

These updates include:
- Fixing the examples for specifying paths with FieldExport
- Switching default instance type to db.t4g.micro
- Updating controller version to v0.0.24

Several updates to the RDS tutorial

---

docs/content/docs/user-docs/install.md

This pull request remove the hardcoded reference do s3 service

Remove hardcoded service reference in documentation

---

docs/content/docs/tutorials/rds-example.md

Description of changes: This brings in the v0.0.27 release, which includes the updated API.

Bump version of RDS controller in tutorial

---

docs/content/docs/user-docs/adopted-resource.md

Closes https://github.com/aws-controllers-k8s/community/issues/965
Add documentation, as part of the user docs, for the `AdoptedResource` CRD. 

Create adopted resource docs

---

docs/content/docs/contributor-docs/testing.md

Updates the contributor testing docs to use the new declarative config, and generally updates some of the best practices and information.

Update testing doc for declarative config

---

docs/content/docs/tutorials/aurora-serverless-v2.md

This tutorial fixes a few issues that were identified after the tutorial was
committed. This also includes examples for using both PostgreSQL and MySQL.

Updates to the Aurora Serverless v2 tutorial

---

docs/content/docs/tutorials/aurora-serverless-v2.md

Updating Serverless tutorial, engineVersion needs to be string

---

docs/content/docs/user-docs/ack-tags.md

* Add docs for ACK default tags

Add docs for ACK default tags

---

docs/content/docs/tutorials/aurora-serverless-v2.md
docs/content/docs/tutorials/rds-example.md

1. Changing DB subnet name all lowercase.
2. Changing security group name to all lowercase
3. Fixing syntax for rds-pods.yaml ( added container and image name and fixed)

Fixes for Serverless and RDS turorial

---

docs/content/docs/tutorials/rds-example.md

This adds a section on how to deploy a RDS for MySQL DB from ACK.

Add additional content to RDS tutorial

---

docs/requirements.txt

Issue https://github.com/aws-controllers-k8s/community/issues/1424
- [docs] Upgrade `acktools` version
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

[docs] Upgrade `acktools` version

---

docs/content/docs/tutorials/sagemaker-example.md

update sagemaker tutorial to use latest controller version

---

docs/content/docs/tutorials/sagemaker-example.md

update yq tool installation link in sagemaker tutorial

---

docs/content/docs/tutorials/lambda-oci-example.md

Change lambda tutorial `title`, `description` and `lead`
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

Change lambda tutorial `title`, `description` and `lead`

---

docs/content/docs/tutorials/sagemaker-example.md

update SM controller version in tutorial

---

docs/content/docs/tutorials/sagemaker-example.md

Wait for https://github.com/aws-controllers-k8s/sagemaker-controller/pull/167 to be merged

 update SM controller version in tutorial

---

GOVERNANCE.md
README.md
docs/content/docs/community/discussions.md

Signed-off-by: Baiju Muthukadan <baiju.m.mail@gmail.com>
Issue #, if available: https://github.com/kubernetes/community/pull/6763

Update the Slack channel

---

docs/content/docs/community/how-it-works.md

Description of changes: Add docs on drift remediation
Signed-off-by: Jonathan S. Katz <jkatz@amazon.com>

Add docs on drift remediation

---

docs/content/docs/tutorials/rds-example.md

add dbproxy in RDS example doc as supported CRD 

Add dbproxy in rds example supported CRD

---

docs/content/docs/tutorials/emr-on-eks-example.md

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1452
Description of changes: We are announcing developer preview for ACK service controller for EMR on EKS. This tutorial would walk the customers through how to create EMR on EKS controller and run Spark Jobs

adding tutorial for emr on eks controller

---

docs/content/docs/tutorials/emr-on-eks-example.md

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1452
Original PR #: https://github.com/aws-controllers-k8s/community/pull/1453
Description of changes: minor edits to fix links and grammer

minor edits for emr on eks tutorial

---

docs/content/docs/tutorials/emr-on-eks-example.md

Updating the EMRContainer tutorial to include the new `configurationOverrides`
field introduced in v0.0.9.

[emr-containers] adding new features to tutorial

---

docs/content/docs/contributor-docs/tenets.md

Description of changes: fixing a small typo in tenets.md

fix typo in tenets.md

---

docs/content/docs/tutorials/emr-on-eks-example.md

Description of changes: correcting job execution policy for walk-through and for upcoming blog post

fixing minor issue with job policy

---

docs/content/docs/tutorials/emr-on-eks-example.md

Description of changes: Announcing GA

Announcing GA for ACK controller for EMR on EKS

---

docs/content/docs/contributor-docs/code-generator-config.md

Issue #, if available: [1502](https://github.com/aws-controllers-k8s/community/issues/1502)
Further updates to "Understanding generator.yaml Configuration"; this draft includes additional content, most notably in the sections on field-level configuration, hooks for controlling comparison, and field mutability.

Third draft of "Understanding generator.yaml Configuration"

---

docs/content/docs/user-docs/deletion-policy.md

Adds a page to the `Getting Started` section of the user docs with information about the new deletion policy feature

Add a user doc page for deletion policy

---

docs/content/docs/tutorials/autoscaling-example.md
docs/content/docs/tutorials/sagemaker-example.md

Updates version of Sagemaker/Application autoscaling controller in tutorials.

Updated Sagemaker tutorial

---

docs/content/docs/user-docs/deletion-policy.md

IMO this is more intuitive to read, highest precedence first. Let me know your thoughts

update wording for deletion policy configuration order

---

docs/content/docs/contributor-docs/setup.md

Updates the contributor setup documentation to require a minimum Go version

Add notice for minimum Go version

---

docs/content/docs/contributor-docs/code-generator-config.md

Made some small additions to the headings in this document to make the TOC easier to navigate

Minor tweaks to headings in "Understanding generator.yaml configuration"

---

docs/requirements.txt

Updates the `requirements.txt` to include the latest commit in `acktools`

Update the `acktools` dependency

---

docs/content/docs/tutorials/sqs-example.md

Issue #, if available: #1704
Description of changes: Add basic `SQS` tutorial

docs: Add basic `SQS` tutorial

---

README.md

Set community meeting time to 16:00 UTC
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

Set community meeting time to 16:00 UTC

---

docs/content/docs/tutorials/pipes-example.md
docs/content/docs/tutorials/sqs-example.md

Description of changes: Add `Pipes` tutorial

Add Pipes Tutorial

---

docs/content/docs/tutorials/eventbridge-example.md
docs/content/docs/tutorials/pipes-example.md

Description of changes: Add `Eventbridge` tutorial and minor fixes in `Pipes` tutorial.

Add `Eventbridge` Tutorial

---

docs/content/docs/tutorials/memorydb-example.md

Issue #, if available: Update ACK MemoryDB controller tutorial
Description of changes: Updated ACK MemoryDB controller tutorial

Update ACK MemoryDB controller tutorial

---

docs/content/docs/community/faq.md

https://github.com/aws-controllers-k8s/community/issues/1759
Title says it.

Add a FAQ entry about foreground cascading deletion

---

docs/content/docs/user-docs/leader-election.md

Add controllers leader election documentation

Add controllers leader election documentation

---

docs/requirements.txt

Pin `ack/test-infra/tools` to `809a5972c712a59f51d407efb553d55fab126c62`

---

README.md

Tired of all these timezone changes..

Set ACK Community meeting time to 9:00AM PST

---

ADOPTERS.md

Adding adopters file to the project.
Created a place holder entry, for the first user that will be added

Adding ADOPTERS file to the project

---

ADOPTERS.md

Description of changes:  Added Adobe to the list in `ADOPTERS.md`.

Adding Adobe to the Adopters list

---

docs/requirements.txt

Pin `test-infra/tools` to c1307f6b3cf599b6920121490f4cd8136ac645f0

---

docs/requirements.txt

Pin test-infra/tools to `b9b2416624a69edc47f0aeaed34efac5d02b8673`

---

docs/requirements.txt

Pin test-infra/tools to `20880d772074520896f26efe4861342da4b21b30`

---

docs/content/docs/user-docs/irsa.md

Replace usage of recommended policies with example policies

---

docs/requirements.txt
docs/scripts/gen_services.py

Pin acktools to 37943dd8dd38544ab7b901af762998b625a1cdd9

---

docs/requirements.txt

Pin acktools to 0585d0671b593e1b1a1d070614af41eb022c695a

---

docs/design/proposals/security-patches/security-patches.md

[Design] Security Patches and CVE scanning for ACK

---

README.md

Update community meeting frequency

---

docs/content/docs/user-docs/adopted-resource.md
docs/content/docs/user-docs/features.md

Adding a description and examples for the current 
features we support behind a feature flags.

Add doc for alpha features

---

docs/content/docs/user-docs/adopted-resource.md

fixes https://github.com/aws-controllers-k8s/community/issues/2382
- added full adoption link.

fix adoption doc link

---

.github/workflows/issue-response.yml

- Temp Solution until the Prow Plugin needed is ready
- eg: https://github.com/ack-prow-staging/community/issues/19

Create Github issue response action

---

docs/content/docs/user-docs/features.md

fix: typo in adoption via annotations documentation

---

docs/content/docs/user-docs/openshift.md

Issue #, if available: #2537
Added FEATURE_GATES to ConfigMap documentation, because it is required as described in the issue #2537 

Add FEATURE_GATES to ConfigMap documentation
