aws-controllers-k8s/community

docs/code-generation.md

Correct the statement about multiple API groups not being supported in V2 of `kubebuilder`. As of https://github.com/kubernetes-sigs/kubebuilder/pull/1198 `kubebuilder` allows for multi-group in the same repository.
*Issue #, if available:*
*Description of changes:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Correct Kubebuilder Multi-Group Statement

---

go.mod
go.sum
pkg/names/names.go
pkg/names/names_test.go
pkg/resource/enum_def.go
pkg/resource/resource.go
pkg/resource/type_def.go
templates/enum_def.go.tpl
templates/resource.go.tpl
templates/type_def.go.tpl

In generating type definitions for various service APIs, I noticed the
normalization of names for fields and structs had a few errors. For
example, in the RDS API, the following are all field names:
* DBInstanceIdentifier
* DbInstanceIdentifier
* DBInstanceId
* DbiResourceId
Pay attention to the slight case differences and the use of the word
"Identifier" and "Id" or "ID"...
This commit adds fixes for incorrect normalization that was, for
example, outputting "DbInstanceIDentifier" or "dBiResourceID".

correct naming normalization problems

---

pkg/model/enum_def.go
pkg/schema/attr.go
pkg/schema/enum_def.go
pkg/schema/util.go
templates/enum_def.go.tpl

Two commits with fixes for some errors encountered during type and enum definition generation. First commit corrects the Go type output for enum definitions. Second commit corrects improper array of object Go type output and where I was passing the wrong Schema object for certain object-like attributes.

fixes for enum and type definition generation

---

pkg/schema/crd_test.go
pkg/schema/testdata/topic-api.yaml

Adds simple unit test for the schema helper's GetCRDS() method using a
simplified SNS-like API fixture.

start adding schema-parsing unit tests

---

services/bookstore/pkg/resource/book/descriptor.go
services/bookstore/pkg/resource/book/identifiers.go
services/bookstore/pkg/resource/book/manager.go
services/bookstore/pkg/resource/book/manager_factory.go
services/bookstore/pkg/resource/book/manager_factory_test.go
services/bookstore/pkg/resource/book/resource.go

Varun noticed in testing that the ManagerFor() method of the
bookResourceManagerFactory struct was throwing a nil pointer exception
due to the rmCache field not being properly initialized to a valid map.
This patch fixes that problem by ensuring that the resource manager
factory registered in init() has a properly initialized rmCache.

Make sure that rmCache is initialized

---

scripts/lib/common.sh
scripts/lib/helm.sh
scripts/run-integration-tests.sh
services/petstore/Dockerfile

* Using the temporary docker hub images and helm charts to start service controllers inside the EKS cluster as proof of concept.
* Using this temp repo (https://hub.docker.com/repository/docker/errorbyte/ack) to build helm charts ( https://vijtrip2.github.io/aws-service-operator-k8s/helm/charts/ ) 
--------------
* I will update the helm chart to use ECR repository from integration test
* @varun1524 will add the logic of building images for the latest commit and uploading to above mentioned ECR repository

Using helm to initialize service controllers for integration-test.

---

pkg/schema/attr.go
pkg/schema/crd.go
pkg/schema/helper.go
pkg/schema/testdata/complex-types.yaml
pkg/schema/type_def.go
pkg/schema/util.go
pkg/schema/util_test.go

When determining the Go type for schemas of type "object" or "array of
object", we were searching for the referred-to schema using the wrong
name. For the case of schemas with a type of "object", we were passing
the name of the property, camel-cased. In the case of the "array of
object" type schemas, we were using the name of the property instead of
the name of the schema being referred to.
What this meant was that, for example, the ECR API's ImageScanFindings
object's "findings" property, which looks like this:
```yaml
ImageScanFindings:
properties:
findingSeverityCounts:
$ref: '#/components/schemas/FindingSeverityCounts'
findings:
$ref: '#/components/schemas/ImageScanFindingList'
imageScanCompletedAt:
$ref: '#/components/schemas/ScanTimestamp'
vulnerabilitySourceUpdatedAt:
$ref: …
```

correct lookup of referred-to object schemas

---

mocks/pkg/types/aws_resource_manager.go
pkg/types/aws_resource_manager.go
services/bookstore/pkg/resource/book/descriptor.go
services/bookstore/pkg/resource/book/identifiers.go
services/bookstore/pkg/resource/book/manager.go
services/bookstore/pkg/resource/book/manager_factory.go
services/bookstore/pkg/resource/book/resource.go
services/petstore/pkg/resource/pet/descriptor.go
services/petstore/pkg/resource/pet/identifiers.go
services/petstore/pkg/resource/pet/manager.go
services/petstore/pkg/resource/pet/manager_factory.go
services/petstore/pkg/resource/pet/resource.go
templates/pkg/crd_descriptor.go.tpl
templates/pkg/crd_identifiers.go.tpl
templates/pkg/crd_manager_factory.go.tpl
templates/pkg/crd_resource.go.tpl

Originally, I'd had the controller code generators outputting the
different resource managers, manager factories, identifiers and
descriptors into a single `services/$SERVICE/pkg/resource` package. This
is why the templates for generating those CRD-specific objects prefixed
each object with the CRD's Kind. For example, the Book's resource
manager struct was called bookResourceManager.
I switched the code generators to output each CRD into its own separate
Go package (e.g. `services/bookstore/pkg/resource/book`) but kept the
CRD name prefix on the structs defined in the package. This caused the
templates to be unnecessarily verbose and less readable.
With this patch, I've removed that CRD name prefix on the individual
resource package's structs, so every CRD's resource package has …

remove CRD name prefix in resource pkg objects

---

pkg/model/crd.go
pkg/schema/crd.go
pkg/schema/crd_test.go
pkg/schema/helper.go
pkg/schema/op.go
pkg/schema/op_test.go
services/bookstore/pkg/resource/book/manager.go
services/petstore/pkg/resource/pet/manager.go

Following patches rely on being able to determine the payload of an
operation in order to generate the appropriate SDK-specific objects in
the AWSResourceManager templated code. This patch creates a map, keyed
by operation type (e.g. OpTypeCreate, OpTypeGet, etc) and resource name
(the Kind of the CRD) to an *openapi3.Operation struct that the
templates will use to query for payload information.
This patch also changes the resource manager implementation to split out service
SDK-specific HTTP request payload construction (for Create, Read, Update
and Delete APIs) into a separate helper method where we can isolate the
service-specific code better.

collate all Operations for a CRD from schema

---

pkg/schema/testdata/complex-types.yaml
pkg/schema/util.go
pkg/schema/util_test.go

The RDS API's DBCluster resource has a schema that looks like this:
```yaml
DBCluster:
properties:
... lots of other fields ...
DBClusterOptionGroupMemberships:
$ref: '#/components/schemas/DBClusterOptionGroupMemberships'
DBClusterOptionGroupMemberships:
items:
properties:
DBClusterOptionGroupName:
$ref: '#/components/schemas/String'
Status:
$ref: '#/components/schemas/String'
type: object
type: array
```
Note that there is no "DBClusterOptionGroupMembership" struct.
Many AWS APIs needlessly (due to XML legacy) wrap arrays of some
singular object in structs that are nothing more than a struct with a
single field that is an array of the singular object type. There is code
in ACK that looks for this situation and "unwraps" those needless
wrapper structs and makes the end Go type in the …

fix pluralized referred-to object types in arrays

---

cmd/ack-generate/command/apis.go
cmd/ack-generate/command/controller.go
pkg/model/crd.go
pkg/model/type_def.go
pkg/template/apis/types.go
templates/apis/crd.go.tpl
templates/apis/enums.go.tpl
templates/apis/type_def.go.tpl
templates/apis/types.go.tpl
templates/pkg/crd_resource.go.tpl

This PR fixes two issues found while generating the ECR service controller
and building the service controller.
The first issue was that the template variables used to generate the
`cmd/controller/main.go` file were not lowercasing the service alias, so an
improper import path of:
```
svcapitypes "github.com/aws/aws-controllers-k8s/services/ECR/apis/v1alpha1"
```
was being generated. There was also a typo of "service" instead of "services" in another
template's import paths.
The second issue I found was due to certain type definitions or fields in CRD `Status`
or `Spec` structs used types that were not builtins. For example, the `CreateTime`
field in the `Repository.Status` CRD struct is of type `*time.Time`. We were not importing
the `time` package in the `types.go` file or the CRD …

fix build errors in controller and apis generation

---

pkg/model/crd.go
pkg/model/enum_def.go
pkg/model/type_def.go

There were issues with enum and type names that conflicted with the
CRD's Spec and Status types. For instance, in the RDS API there is a
DBProxyStatus enum type that conflicts with the DBProxy CRD's Status
field type, which is `type DBProxyStatus struct`. We identify these
conflicting names and suffix the generated types with "_SDK".
Secondly, I was not generating the proper Go types properly. I need to
use the normalized Camel-cased name of the struct or list element type
instead of the name returned by
aws-sdk-go/private/model/api.Shape.GoTypeWithPkgName().
Fixes Issue #89

fix struct name conflicts and Go type cleaning

---

pkg/model/type_def.go

Issue #94 , if available:
Append _SDK to type_def when type name collides with CRD name.
```
vijat@186590cff3cf aws-controllers-k8s % ./scripts/build-controller.sh apigatewayv2
Building Kubernetes API objects for apigatewayv2
Generating deepcopy code for apigatewayv2
Building service controller for apigatewayv2
```

Append _SDK to type_def when type name collides with CRD name.

---

pkg/model/type_def.go

We were excluding type definition generation for Shapes that had the
same name as a CRD, however this was incorrect. Instead, we need to
rename the type definition to ensure it doesn't conflict with the CRD
struct name. We still need to use these type definitions when
constructing SDK linkage.
Specifically, when generating the service controller for APIGatewayV2, a
number of type definitions that represent the returned object
representation from ReadMany operations (List) were not being written to
the types.go file. Examples of this include Deployment, Stage, Route,
Model, etc.
These type definitions are now included:
```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ tree services/apigatewayv2/apis/v1alpha1/
services/apigatewayv2/apis/v1alpha1/
├── api.go
├── api_mapping.go …
```

include TypeDef names same as CRDs

---

go.mod
go.sum
pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/helper.go
pkg/model/testdata/models/apis/apigatewayv2/0000-00-00/api-2.json
pkg/model/testdata/models/apis/apigatewayv2/0000-00-00/docs-2.json
pkg/model/type_def.go
pkg/model/type_def_test.go
scripts/lib/k8s.sh
templates/pkg/crd_sdk.go.tpl

Fixes a series of mistakes in the sdk.go generation of struct-fields and
array-fields for the Go code that constructs and initializes SDK Input
shapes as well as CRD Status structs.
we construct variables containing temporary storage for sub-elements
and sub-fields that are structs. Names of fields are "f" appended by
the 0-based index of the field within the set of a struct's set of
fields. Nested structs simply append another "f" and the field index
to the variable name.
This means you can tell what field a temporary fields variable
represents by the name.
For example, the field variable name "f0f5f2", it contains the third
field of the sixth field of the first field of the input shape being
constructed.
If we have two levels of nested struct fields, we will end
up with a targetVarName …

correct sdk.go code generation

---

pkg/names/names.go
pkg/names/names_test.go

Update the initialism table, to correctly clean names containing the following special words: `Security` and `Idle`
Fixes #90 and #97

Support name cleaning for some special cases

---

pkg/names/names.go
pkg/names/names_test.go

Some tests were failing after #107 merge. The 'Uri' associated regex expression`(?!sec)uri(?!ty)` wasn't enough to catch text that contains camel cased `Uri`.

Fix name initalism for texts that contains 'Uri'

---

cmd/ack-generate/command/apis.go
cmd/ack-generate/command/controller.go
cmd/ack-generate/command/root.go
go.mod
pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/generator_config.go
pkg/model/helper.go
pkg/model/testdata/models/apis/sns/0000-00-00/generator.yaml
pkg/model/testdata/models/apis/sqs/0000-00-00/generator.yaml
pkg/testutil/schema_helper.go

We needed a way of informing the code generator that certain APIs use
"special" handling of certain fields for resources by using an
"Attributes" `map[string]*string` that contains actual, schema'd fields
for the resource.
An example of this type of special API is SNS API which has a
CreateTopic call that defines a Topic resource. The CreateTopic call has
an "Attributes" parameter that contains a set of key/value pairs for
fields such as "DeliveryPolicy" or "DisplayName".
We want to inform the code generator that these fields are contained in
the Attributes parameter and should be "unpacked" into the CRD
definition as top-level fields on the resource.
This patch introduces this functionality by creating a GeneratorConfig
struct that is represented as a YAML file that contains instructions …

introduce framework for handling "special" APIs

---

cmd/ack-generate/command/controller.go
pkg/model/helper.go
pkg/template/cmd/controller_main.go
pkg/template/pkg/resource_registry.go
templates/cmd/controller/main.go.tpl
templates/pkg/resource_registry.go.tpl

Issue #110 , if available:
* While adding import for each CRD in registry.go as per original suggestion, there were errors for circular imports.
* resource package(registry) had dependency on CRD package
* CRD package had dependency on resource to register the resource manager.
So I added the CRD specific imports in main.go and now controller is picking up all the CRD resource manager during build now.

Adding import for CRD packages to register resource-manager-factories

---

pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/op.go
pkg/model/testdata/models/apis/sns/0000-00-00/generator.yaml
pkg/model/testdata/models/apis/sqs/0000-00-00/generator.yaml
pkg/template/pkg/crd_sdk.go
templates/pkg/crd_sdk.go.tpl

Adds generation for Go code that sets the Input shape for GetAttributes
operations or sets CRD Status fields from the Output shape of a
GetAttributes operation.
We add special handling for the primary resource ARN and the AWS Owner
Account ID attribute keys, if found in the Attributes map. For these
special cases, we route the returned Output shape attribute key to the
`Status.ACKResourceMetadata.ARN` and
`Status.ACKResourceMetadata.OwnerAccountID` fields respectively.
Issue #109

generate code for GetAttributes input/output

---

pkg/errors/error.go
pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/testdata/models/apis/sns/0000-00-00/generator.yaml
pkg/template/pkg/crd_sdk.go
scripts/build-controller.sh
templates/pkg/crd_sdk.go.tpl

When constructing the SNS and SQS controllers, ran into some build
failures, including type conversion issues to/from
string/ackv1alpha.AWSResourceName, unused variable errors when there
were no fields being set in an input or output shape, and import issues
with the aws-sdk-go/aws/errors package.
This patch fixes all the above issues and corrects the build of the SNS
and SQS generated service controllers.
You can test the SNS or SQS service controller build by calling:
```
make build-ack-generate
ACK_GENERATE_CONFIG_PATH=pkg/models/testdata/models/apis/sns/0000-00-00/generator.yaml \
./scripts/build-controller.sh sns
make test
```

fix build errors from attribute-map sets

---

pkg/model/crd.go
pkg/model/crd_test.go

This PR contains fixes for three separate issues in the code generation.
The Go code being generated for scalar elements within a list field was
missing the constructor, so, for example, the generated code looked
something like this:
```go
f7 := []*string{}
for _, f7iter := range resp.MyListField {
f7elem.f7 = f7iter
f7 = append(f7, f7elem)
}
```
which of course causes compilation failures to bubble up during `go
build`:
```
undefined: f7elem
```
This patch fixes the code generation for list elements that are scalar
types so that the correct code being output is this:
```go
f7 := []*string{}
for _, f7iter := range resp.MyListField {
var f7elem string
f7elem = *f7iter
f7 = append(f7, &f7elem)
}
```
We were not generating Go code for `map` types. This patch adds support
for outputting Go …

correct issues with Go code generation

---

docs/contents/dev-docs/setup.md
docs/contents/dev-docs/testing.md
scripts/build-controller.sh
scripts/delete-kind-cluster.sh
scripts/kind-build-test.sh
scripts/lib/helm.sh
scripts/lib/k8s.sh
scripts/lib/kind.sh
scripts/provision-kind-cluster.sh

* Makes the use of variables at top of each script consistent
* Uses ensure_XXX functions to ensure that required binaries are present
on the system
* Removes the "OVERRIDE" functionality in the
`scripts/kind-build-test.sh`, `scripts/provision-kind-cluster.sh` and
`scripts/delete-kind-cluster.sh` script. Instead, uses ensure_XXX
functions and just makes sure the required dependencies are available on
the host system
* Removes unused variables and extraneous echo statements
* Update dev-docs appropriately

cleanup and make build/test scripts consistent

---

cmd/ack-generate/command/controller.go
docs/contents/dev-docs/testing.md
pkg/template/config/controller/deployment_yaml.go
pkg/template/config/controller/kustomization_yaml.go
pkg/template/config/default/kustomization_yaml.go
pkg/template/config/rbac/cluster_role_binding_yaml.go
pkg/template/config/rbac/kustomization_yaml.go
scripts/build-controller.sh
scripts/kind-build-test.sh
scripts/lib/k8s.sh
scripts/provision-kind-cluster.sh
templates/config/controller/deployment.yaml.tpl
templates/config/controller/kustomization.yaml.tpl
templates/config/default/kustomization.yaml.tpl
templates/config/rbac/cluster-role-binding.yaml.tpl
templates/config/rbac/kustomization.yaml.tpl
templates/pkg/crd_manager.go.tpl

Adds all the RBAC, Deployment, Namespace and other config file
requisites into the generation of an ACK service controller. This moves
the generated config files into a `services/$SERVICE/config` directory
(out of the `services/$SERVICE/apis/v1alpha1/config/crd` directory)
along with a set of kustomize overlay directories and kustomization.yaml
files.
The `scripts/kind-build-test.sh` has been updated to use kustomize to
generate a templatized overlay directory during testing which points to
the Docker image for the ACK service controller built during the test
run. All configs are then `kubectl apply`'d to the k8s cluster running
in KinD:
```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ rm -rf services/ecr/
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ …
```

generate all config files needed for deployment

---

pkg/model/crd.go
pkg/model/crd_test.go
templates/pkg/crd_sdk.go.tpl

We were only attempting to set the fields on an Input shape by looking
for a corresponding field in the CRD's Spec struct. This makes sense in
a way, since constructing, for example, the CreateBookInput shape would
by nature only take fields from the Book's desired state (i.e. the
BookSpec) struct.
However when constructing Input shapes like that used for ReadOne
operations, we need to look in the CRD's Status fields as well as the
Spec fields.
For example, consider the API Gateway V2 API's GetApiInput shape:
```go
type GetApiInput struct {
_ struct{} `type:"structure"`
// ApiId is a required field
ApiId *string `location:"uri" locationName:"apiId" type:"string" required:"true"`
}
```
The Go code we were outputting for the `newDescribeRequestPayload()`
method in that generated service …

construct Input shape from both Spec and Status

---

pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/generator_config.go
pkg/model/testdata/models/apis/elasticache/0000-00-00/generator.yaml

Issue #, if available: #133 
Description of changes: Added support to ignore resources, operations for AWS Service API controller generation via generator config YAML file

Ability to filter service APIs for controller auto generation #133

---

docs/mkdocs.yml

Description of changes: this fixes the recent [mkdocs upgrade](https://squidfunk.github.io/mkdocs-material/upgrading/#upgrading-from-4x-to-5x). Make sure you're using version `1.1.2` or above, going forward.

fixes docs config, ups to 5.x

---

go.mod
go.sum
pkg/model/crd.go
pkg/model/crd_test.go

When generating the Go code for input shape construction, we were
assuming fields on source variables (CR, CR.Spec and CR.Status objects)
were non-nil. This patch adds nil guards to the generated code to
prevent NPEs.
Issue #127

place nil guards on input shape code generation

---

Makefile
docs/contents/dev-docs/testing.md
scripts/kind-build-test.sh
scripts/lib/aws.sh
scripts/provision-kind-cluster.sh

local functional testing

---

Makefile
pkg/errors/error.go
templates/pkg/crd_sdk.go.tpl

Adds a NotImplemented error return for the ReadMany code path in the
sdk.go generated code. This will at least allow the create code path to
properly error out (issue #152) instead of returning an empty result and
nil error.
Issue #152

add NotImplemented for ReadMany code path

---

pkg/model/crd.go
pkg/model/crd_test.go
pkg/template/pkg/crd_sdk.go
templates/pkg/crd_sdk.go.tpl

Generate the Go code that constructs the Input shapes for List/ReadMany
operations and processes the Output shapes of those ReadMany operations
into the Spec and Status structs of the target CRs.

implement ReadMany code path

---

scripts/kind-build-test.sh

Script was failing because we forgot to import lib/aws.sh

Missing source lib/aws.sh

---

mocks/pkg/types/aws_resource_manager_factory.go
mocks/pkg/types/aws_resource_reconciler.go
pkg/runtime/reconciler.go
pkg/types/aws_resource_manager.go
pkg/types/aws_resource_reconciler.go
services/bookstore/pkg/resource/book/manager.go
services/bookstore/pkg/resource/book/manager_factory.go
services/bookstore/pkg/resource/book/manager_factory_test.go
services/petstore/pkg/resource/pet/manager.go
services/petstore/pkg/resource/pet/manager_factory.go
services/petstore/pkg/resource/pet/manager_factory_test.go
templates/pkg/crd_manager.go.tpl
templates/pkg/crd_manager_factory.go.tpl

We need a way of allowing the resource manager to get Kubernetes object
information for things like Kubernetes Secrets. However, I deliberately
did not want to pass the Kubernetes client objects into the resource
managers (since their job is to handle the SDK linkage, not to query
Kubernetes API).
However, the resource manager will need at least the ability to grab a
value for a SecretReference, and in order to facilitate this, I changed
the `AWSResourceManagerFactory.ManagerFor` interface method to pass in
an object that implements the `AWSResourceReconciler` interface. I then
added a stub `AWSResourceReconciler.SecretValueFromReference()`
interface method (for Alina to implement) into the runtime's Reconciler
concrete struct. The resource managers now have an `rr` field that
points to …

plumb reconciler into resource manager

---

pkg/model/crd.go
pkg/model/crd_test.go
pkg/template/pkg/crd_sdk.go
scripts/build-controller-image.sh
scripts/kind-build-test.sh
scripts/lib/aws.sh
templates/config/controller/deployment.yaml.tpl
templates/pkg/crd_sdk.go.tpl

The templated sdk.go file was looking for the string "NotFoundException"
to identify whether a call to an AWS API was returning a 404 NotFound.
Unfortunately this isn't correct for most APIs, including Elasticache.
The exception codes in Elasticache look like "CacheClusterNotFound"
instead of the generic "NotFoundException". Trying to match on the
string "NotFound" doesn't work either, since calls to, for example, the
DescribeCacheClusters API call legitimately return 400 with a code of
"ServiceLinkedRoleNotFound" which is actually a permissions problem.
This patch adds a `CRD.NotFoundException()` method which looks through
the read-like API calls for Error codes and looks for 404 HTTP status
codes and writes the matched exception code string into the sdk.go
template instead of the …

properly handle NotFoundException in reads

---

pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/generator_config.go
pkg/model/testdata/models/apis/codedeploy/0000-00-00/generator.yaml
pkg/model/testdata/models/apis/dynamodb/0000-00-00/generator.yaml
pkg/model/testdata/models/apis/ecr/0000-00-00/generator.yaml
pkg/template/pkg/crd_sdk.go
scripts/build-controller.sh
services/codedeploy/generator.yaml
services/dynamodb/generator.yaml
services/elasticache/generator.yaml
services/sns/generator.yaml
services/sqs/generator.yaml
templates/pkg/crd_sdk.go.tpl

Adds a new ExceptionsConfig struct to the GeneratorConfig. This new
struct provides instructions to the code generator on how to identify
the Exception "Code" for a returned string error message for a
particular API resource's ReadOne/ReadMany/GetAttributes operations.
The `CRD.NotFoundException()` method has been changed to
`CRD.ExceptionCode()` and now accepts an HTTP status code that the
caller wants the string Exception code for a particular resource.
I've gone ahead and git add'd `generator.yaml` files for each of the
APIs where we've needed to give the code generator special instructions
into the `service/$ALIAS/generator.yaml` location. This will solve the
common problem that folks have been running into where they try
generating an API and run into errors like this:
```
error …
```

add ExceptionsConfig instructions for code gen

---

Makefile
scripts/kind-build-test.sh
scripts/lib/common.sh
scripts/lib/k8s.sh
scripts/lib/testutil.sh
test/e2e/ecr/smoke.sh
test/e2e/run-tests.sh

Adds a new Bash-based e2e test framework that can be integrated (at a
later point, as needed) with the `scripts/kind-build-test.sh`.
The first e2e test is a very simple ECR repository "smoke test" which
does the following:
1) check if a particular ECR repository exists via the `aws` CLI
tool
2) check if that ecr.services.k8s.aws/Repository CR exists via
`kubectl`
3) creates the ecr.services.k8s.aws/Repository CR via `kubectl`
4) verifies the ECR Repository was created via the `aws` CLI tool
5) deletes the ecr.services.k8s.aws/Repository CR via `kubectl`
6) verifies the ECR Repository no longer exists via the `aws` CLI tool
To run the new e2e test script for ECR, do this:
```
export ROLE_ARN="the ARN of the AWS Role you will use for testing"
make build-ack-generate …
```

adds Bash-based e2e test framework and ECR test

---

templates/pkg/crd_sdk.go.tpl

We were missing an else if statement in the sdk.go template, causing
failures when generating the RDS service controller.

was missing an else-if in SDK template

---

pkg/model/crd.go
pkg/model/crd_test.go

When generating Go code that sets the Spec or Status fields of a CR from
the response Output shape of a List/ReadMany operation, we were
failing to use the "cleaned" names for Kubernetes API types in the
`CRD.goCodeVarEmptyConstructorK8sType()` method. While we were properly
looking up to see if the Shape had to be renamed (due to conflicts with
core objects like the CRDStatus or CRDSpec types), we were not cleaning
the type definition names for struct, map[string]*struct, or []*struct
types. This patch fixes that and adds unit tests of the RDS DBInstance
ReadMany output Go code generation to ensure properly cleaned type names
are used.
Fixes Issue #169
A second issue was identified when generating the RDS service
controller: there are actually API top-level resources that have a
Create …

address issues in ReadMany generated output code

---

Makefile
scripts/build-controller-image.sh

In learning to build the project it's helpful, for me, to have a `make help` target with descriptions of what the targets do. I also added a target to build one of the container images and in the build-controller-image.sh script export `DOCKER_BUILDKIT=1` because builds are faster (and look better).
cc @nithu0115

Add make help and build-controller-image targets

---

pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/generator_config.go
pkg/model/testdata/models/apis/s3/0000-00-00/generator.yaml
scripts/kind-build-test.sh
services/s3/generator.yaml
test/e2e/ecr/smoke.sh
test/e2e/s3/smoke.test

The S3 CreateBucket API Operation has an Input shape with a field called
"Bucket". This is actually the *name* of the Bucket to be created.
Unfortunately, the ListBuckets API Operation's Output shape (from which
we build the SDK linkage to find a particular object) calls this same
field "Name" (quite appropriately I might add, since that's what the
field represents... the bucket's name).
In order to handle mismatched field names like this, I have added a
`RenamesConfig` struct to the `GeneratorConfig` that holds instructions
on how to rename certain fields in the input and output shapes.
The S3 `generator.yaml` config has been modified with the following
rename instructions:
```yaml
resources:
Bucket:
renames:
operations:
CreateBucket:
input_fields:
Bucket: Name
```
which effectively …

S3 service controller enhancements and fixes

---

apis/core/v1alpha1/common.go
mocks/pkg/types/aws_resource_manager.go
mocks/pkg/types/aws_resource_manager_factory.go
pkg/model/crd.go
pkg/model/crd_test.go
pkg/model/generator_config.go
pkg/model/type_def.go
pkg/runtime/reconciler.go
pkg/types/aws_resource_manager.go
scripts/kind-build-test.sh
scripts/lib/aws.sh
services/bookstore/pkg/resource/book/manager.go
services/bookstore/pkg/resource/book/manager_factory.go
services/bookstore/pkg/resource/book/manager_factory_test.go
services/petstore/pkg/resource/pet/manager.go
services/petstore/pkg/resource/pet/manager_factory.go
services/petstore/pkg/resource/pet/manager_factory_test.go
templates/pkg/crd_manager.go.tpl
templates/pkg/crd_manager_factory.go.tpl
test/e2e/s3/smoke.sh
test/e2e/sns/smoke.sh

Quite a few problems with the generation of the SNS service controller.
When I wrote the smoke test for SNS, it identified issues with how the
call to GetTopicAttributes was being incorrectly made. The TopicArn
field in the GetTopicAttributesInput shape was not being set. So, I
added code to set that value to a simulated ARN (when the ARN doesn't
exist yet due to the resource not being created yet in the AWS API, we
can construct an ARN using the AWS account ID and region associated with
the resource manager).
This way, the GetTopicAttributes API call will return a 404 as
appropriate and the sdkFind() code paths will work properly.
I'm still, however, getting failures when attempting to run the smoke
tests. I'm getting the following error:
```
2020-08-17T01:22:53.772Z	ERROR …
```

SNS service controller codegen fixes

---

docs/contents/dev-docs/testing.md
test/e2e/ecr/smoke.sh

The `aws` CLI tool apparently changed from using return code 255 to
using return code 254 between v1 and v2 of the CLI tool. So, this
modifies the ECR smoke test to simply check for either of those return
codes when determining if a repository already exists.

check for NotFound using 255 or 254 for ECR

---

scripts/kind-build-test.sh

This reverts commit d5caf9f2d6b4ade34a1d1568427a172e5967d6d4.

Revert "fixing kind-build-test script when no ROLE_ARN is passed"

---

Makefile
scripts/publish-controller-image.sh

To publish images for a service controller, run:
```
./scripts/publish-controller-image.sh -s <SERVICE>
```

Add script that publishes Docker image for ctrlr

---

docs/contents/dev-docs/testing.md

This fixes the fix from https://github.com/aws/aws-controllers-k8s/pull/220
I should have known better that I can't have a `:` after a bash variable. This ended up removing `:r` from the variable.

Add variable separators

---

cmd/ack-generate/command/controller.go
pkg/model/helper.go

Some service alias names contains white spaces, which is causing `controller-gen` to generate controllers files with white spaces in import paths, apis group name...
In this PR we remove white spaces from service alias names and move every name cleaning action to `Helper{}.GetCleanServiceAlias`
List of impacted services:
```bash
"Migration Hub"
"ACM PCA"
"Alexa For Business"
"API Gateway"
"Application Auto Scaling"
"Application Insights"
"App Mesh"
"Auto Scaling Plans"
"Auto Scaling"
"Cost Explorer"
"CloudHSM V2"
"CodeGuru Reviewer"
"CodeStar connections"
"codestar notifications"
"Cognito Identity"
"Cognito Identity Provider"
"Compute Optimizer"
"Config Service"
"Cost and Usage Report Service"
"Device Farm"
"Direct Connect"
"Application …
```

Clean service alias names from white spaces

---

test/e2e/s3/smoke.sh

Bucket names in S3 are globally unique. Currently, the smoke test
for the s3 controller uses a fixed bucket name. This leads to
failures if more than one user is running the smoke test at the
same time.
This change suffixes the smoke test bucket name with the running
users AWS_ACCOUNT_ID, ensuring that the bucket name is unique per
account.
Using a relatively fixed (per user) value ensures that the test
will still detect undeleted buckets/resources for that user, while
preventing interference from others tests.
Testing:
```
make kind-test SERVICE=s3
...
...
...
======================================================================================================
To poke around your test manually:
export …
```

Smoke test S3 bucket creation using per account bucket names

---

services/elasticache/generator.yaml

The attributes of CacheParameterGroup are immutable. This API can be used to update individual key, value
parameters that are part of `CacheParameterGroup`. Without excluding the operation we keep on seeing 
```
2020-08-25T19:28:58.593-0700    ERROR   controller-runtime.controller   Reconciler error        {"controller": "cacheparametergroup", "request": "default/testccr", "error": "InvalidParameter: 1 validation error(s) found.\n- missing required field, ModifyCacheParameterGroupInput.ParameterNameValues.\n"}
```
as Modify operation is continuously invoked.

Exclude ModifyCacheParameterGroup operation from generator.yaml

---

ATTRIBUTION.md
Dockerfile

OK, that took a while...
Went through all our go.mod dependencies including transitive
dependencies and added license and attribution information into an
ATTRIBUTION.md file. This is a necessary thing for us to distribute
along with our Docker images containing ACK service controller binaries.

Adds ATTRIBUTION.md file

---

Dockerfile

Fix dockerfile copy paths for `LICENSE` and `attribution.md`

Fix dockerfile copy paths for LICENSE and attribution.md

---

pkg/runtime/reconciler.go
scripts/lib/testutil.sh
test/e2e/ecr/smoke.sh
test/e2e/elasticache/cache_subnet_group/smoke.sh
test/e2e/s3/smoke.sh
test/e2e/sns/smoke.sh

The `pkg/runtime.reconciler.getAWSResource()` method was ignoring
NotFound errors, which was resulting in returning (nil, nil) from that
function, but functions like `getOwnerAccountID()` were counting on a
non-nil AWSResource.
We modify the code to simply return nil from `reconcile()` when a
resource with a supplied NamespacedName isn't found.
Adds a simple `assert_pod_not_restarted` check to each e2e test that
verifies the controller pod hasn't been restarted.
Issue #257
Issue #166

handle NotFound from kube API

---

Makefile
cmd/ack-generate/command/version.go

Add ldflags parameters to `build-ack-generate` Makefile rule

Add ldflags parameters to build-ack-generate rule

---

.github/dependabot.yaml

Issue #241 
Description of changes: Added Dependabot support for `aws-sdk-go`. Made it weekly because updates to the SDK are frequent enough that daily PRs seemed tedious. Didn't modify any of the default commit messages, labels or add reviewers.

Add dependabot support for aws-sdk-go

---

scripts/lib/k8s.sh

Issue: #273
Description of changes: Adds new function to check for controller-gen binary version, if it already exists and the version is less than the minimum required `v0.3.1`, it exits and throws an error. 

Adds a check for minimum required version for controller-gen binary

---

pkg/generate/config/config.go
pkg/generate/elasticache_test.go
pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
pkg/model/crd.go
services/elasticache/generator.yaml

Some operations input parameters are requiredto be overriden. This change would allow them to be configuredfrom generator.yaml. ElastiCache will use this to override SetApplyImmediately while modifying CacheCluster and ReplicationGroup
This would not solve the maintenance window handling, but allows us to disable it for now.
Issue #, if available: https://github.com/aws/aws-controllers-k8s/issues/229

Implement Override values of Operations

---

apis/core/v1alpha1/resource_metadata.go
pkg/runtime/reconciler.go
templates/apis/crd.go.tpl
templates/pkg/crd_descriptor.go.tpl
templates/pkg/crd_sdk.go.tpl

* make ARN optional in ACKResourceMetadata because some AWS resources do not return this field.
* add `+kubebuilder:subresource:status` tag for successful status patching.

Changes for successful k8s object status patching.

---

pkg/generate/apigwv2_test.go
pkg/generate/sqs_test.go
pkg/generate/template.go
pkg/model/crd.go
templates/pkg/crd_sdk.go.tpl
test/e2e/sqs/smoke.sh

In #271, @vijtrip2 added methods that output Go code that checked if the
Input shape for ReadOne operations for a resource had required fields
and if so, checked that the CR's `Status.{Field}` had a non-nil value,
otherwise the `resourceManager.sdkFind()` method would return
`NotFound`, indicating to callers (in particular when trying to
determine if a newly-created resource already existed) that the backend
AWS resource had not been created yet.
This patch makes that work generic in two ways:
* adds support for when required fields in an Input shape are in the
CR's `Spec` struct in addition to the `Status` struct.
* adds support for any Input shape, not just the ReadOne operation's
Input shape.
For SQS, the GetQueueAttributes' Input shape has required fields
(QueueUrl) that, if not …

NotFound when any required field missing in shape

---

cmd/ack-generate/command/common.go
cmd/ack-generate/command/root.go

Issue #291  
`ack-generate` now will call `git pull` if aws-sdk-go repository already exist in the cache

`ack-generate` call `git pull` if aws-sdk-go repository already exist in the cache

---

Makefile
scripts/build-controller.sh
scripts/build-controllers.sh

Issue #302 
Convert service name to lowercase in `Makefile` and helper script files - `build-controllers.sh` and `build-controller.sh`

Service names arguments are accepted as case insensitive for make commands

---

pkg/generate/config/config.go
pkg/model/crd.go
services/elasticache/config/rbac/cluster-role-binding.yaml
services/elasticache/config/rbac/role.yaml
services/elasticache/generator.yaml
services/elasticache/pkg/resource/replication_group/custom_set_output.go
services/elasticache/pkg/resource/replication_group/sdk.go
templates/pkg/crd_sdk.go.tpl

Issue #282 
Added support for custom set output operations using generator.yaml configuration.
Example:
```
operations:
DescribeReplicationGroups:
custom_set_output_operation: CustomDescribeReplicationGroupsSetOutput
```

Enable custom set output operations

---

Dockerfile

Issue N/A
In the last 24hours building controllers images was failing with the following error:
```
------
> [builder 5/7] RUN  go mod download:
#11 145.6 go: sigs.k8s.io/controller-runtime@v0.6.0 requires
#11 145.6       gomodules.xyz/jsonpatch/v2@v2.0.1: unrecognized import path "gomodules.xyz/jsonpatch/v2": reading https://gomodules.xyz/jsonpatch/v2?go-get=1: 404 Not Found
#11 145.6       server response: 404 page not found
------
```
Apparently there some networking issues with the domain `gomodules.xyz`. Using the Go official proxy is solving the issue.
- Use `GOPROXY=https://proxy.golang.org` in controllers `Dockerfile`

Using the Go official proxy in controllers Dockerfile

---

pkg/generate/config/config.go
pkg/generate/dynamodb_test.go
pkg/generate/ecr_test.go
pkg/generate/elasticache_test.go
pkg/generate/rds_test.go
pkg/generate/sns_test.go
pkg/generate/sqs_test.go
pkg/generate/template.go
pkg/generate/testdata/models/apis/sns/0000-00-00/generator.yaml
pkg/model/crd.go
pkg/runtime/reconciler.go
services/sns/config/rbac/cluster-role-binding.yaml
services/sns/generator.yaml
services/sns/pkg/resource/platform_application/sdk.go
services/sns/pkg/resource/platform_endpoint/sdk.go
services/sns/pkg/resource/topic/sdk.go
templates/pkg/crd_sdk.go.tpl

This patch adds to the code generator for the SDK linkage for APIs that
use the SetAttributes-flavor of updating a resource. Previously, the
`sdk.go` files for these APIs had empty `sdkUpdate` operations with a
big TODO that ended up breaking the service controller (quite
predictably).
While implementing this patch, I stumbled upon yet another unexplainable
inconsistency between two SetAttributes operations within the SNS
service API. The SNS `SetPlatformApplicationAttributes` API call accepts a
field in its Input shape called `Attributes` that is a map of key/value
pairs for attributes to set on the platform application. Unfortunately,
the similarly-named SNS `SetTopicAttributes` API call apparently does
*NOT* work the same way. Instead, there is a single `AttributeName` and …

fix issues with Get/SetAttributes Go code generation

---

.github/workflows/on.pull-request.main.yaml
Makefile

Issue N/A
Add Github action job configuration to generate AWS service controllers
Initial list of generated services: 
- s3
- ecr
- sns
- sqs
- elasticache
- dynamodb
- apigatewayv2

Add Github action job to build AWS service controllers

---

apis/core/v1alpha1/annotations.go
pkg/runtime/cache/account.go
pkg/runtime/cache/account_test.go
pkg/runtime/cache/cache.go
pkg/runtime/cache/namespace.go
pkg/runtime/cache/namespace_test.go
pkg/runtime/reconciler.go
pkg/runtime/registry.go
pkg/runtime/service_controller_test.go
templates/config/controller/deployment.yaml.tpl

Issue #, if available: #102 
Adding functionalities to help caching and accessing CARM configmap and namespace ACK related annotations.

CARM cache implementation

---

pkg/runtime/session.go
services/apigatewayv2/pkg/resource/api/manager.go
services/apigatewayv2/pkg/resource/api_mapping/manager.go
services/apigatewayv2/pkg/resource/authorizer/manager.go
services/apigatewayv2/pkg/resource/deployment/manager.go
services/apigatewayv2/pkg/resource/domain_name/manager.go
services/apigatewayv2/pkg/resource/integration/manager.go
services/apigatewayv2/pkg/resource/integration_response/manager.go
services/apigatewayv2/pkg/resource/model/manager.go
services/apigatewayv2/pkg/resource/route/manager.go
services/apigatewayv2/pkg/resource/route_response/manager.go
services/apigatewayv2/pkg/resource/stage/manager.go
services/apigatewayv2/pkg/resource/vpc_link/manager.go
services/ecr/pkg/resource/repository/manager.go
services/elasticache/pkg/resource/cache_subnet_group/manager.go
services/elasticache/pkg/resource/replication_group/manager.go
services/s3/pkg/resource/bucket/manager.go
services/sns/pkg/resource/platform_application/manager.go
services/sns/pkg/resource/platform_endpoint/manager.go
services/sns/pkg/resource/topic/manager.go
templates/pkg/crd_manager.go.tpl

Description of changes: This change will help us generate session with `ackv1alpha1.AWSRegion` passed via annotation instead of rely on user to pass AWS_REGION environment variable to generate session. 
Along with this, added:
1) Regional endpoint parameter instead of global endpoint. 
* Here we are going to rely on VPC private links and do not allow "custom" endpoint (not the default PrivateLink override to the regional sts endpoint) 

Rely on aws-region cfg or region annotation instead of AWS_REGION variable

---

scripts/publish-controller-image.sh

Issue #322 , if available:
the r option has an argument. specify colon to fix parsing. Now you can specify a non-default different repository on the command line.

the r option has an argument. specify colon to fix parsing

---

scripts/install_mockery.sh

Related to issue #265 
- Install mockery version v1.1.2 instead of v2.2.1
- Support installation for different architectures/os

Improve `install-mockery.sh` script

---

cmd/ack-generate/command/apis.go
cmd/ack-generate/command/controller.go

Handle the case where the supplied alias is named differently in `aws-sdk-go/models/apis`. However, the same supplied alias exists in `...aws-sdk-go/models/apis/*/*/api-2.json` (`serviceId field`).
Issue #, if available: #199 
- Created a Function, that walks through into `aws-sdk-go/models/apis/`
- Reads `api-2.json` for each `service/version` 
- Matches `serviceId` field in `api-2.json` against supplied Service Alias
- If a match, return the dir name just under `aws-sdk-go/models/apis/`. For Example, returns `states` from `~/.cache/aws-sdk-go/models/apis/states/2016-11-23/api-2.json`
- updated `controller` and `apis` to call this Function when, supplied alias returns a **Not found Error in aws-sdk-go/models/apis**
```
$ aws-controllers-k8s git:(sulabh) ✗ …
```

Handle case when supplied alias is named differently in aws-sdk-go/models/apis

---

docs/contents/dev-docs/testing.md

heredoc cannot end with extra space after EOF.
So, how about removing this extra space?

An extra space after EOF should be removed

---

.github/workflows/on.pull-request.main.yaml
Makefile

Issue #, if available: #327 
- Modified the workflow to use `self-hosted` runners
- Included e2e tests in the workflow
- Removed the default mockery version install
- The default version throws error - #265 and #326 
- The runner has `v1.0.1` installed

Added e2e tests in workflow

---

ATTRIBUTION.md
cmd/ack-generate/command/common.go
go.mod

Issue #321
- Add `getSDKVersion` function to extract the aws-sdk-go version to use
- Remove `--depth=1` flag from the `git pull` command to allow easier switches between versions/tags
- Use `git checkout` instead of `git pull`

Use the same aws-sdk-go version mentionned in the go.mod file to generate code

---

pkg/runtime/reconciler.go

Fixes #343
Fix a bug where K/V log pairs were being multiplied at each reconcile call

Fix a bug where K/V log pairs were being multiplied at each reconcile call

---

cmd/ack-generate/command/apis.go
cmd/ack-generate/command/controller.go
cmd/ack-generate/command/root.go

Issue N/A
- Avoid creating directories if a service is not found in aws-sdk-go cache
- Clarify error message when service is not found in aws-sdk-go cache
- Silence usage when user enter correct flags and arguments but command exit with an error
- Avoid double printing the same error, cobra commands already do when use `RunE`: https://github.com/spf13/cobra/blob/master/command.go#L940-L943

Avoid creating directories if a service is not found in aws-sdk-go cache

---

scripts/lib/aws.sh
scripts/lib/aws/ecr.sh
test/e2e/ecr/smoke.sh

The AWS CLI tool version 1.x does not support a variety of more recent
AWS API calls. Case in point: the ECR DescribeRepositories API call does
not return information about the image scanning configuration.
In order to ensure that we have modern versions of the AWS CLI tool
usable in our e2e tests, I've added a `daws` (for Docker AWS) Bash
function that can be used to execute a specific version of the AWS CLI
tool within a Docker container.

use aws CLI in Docker within e2e tests

---

pkg/generate/config/config.go
pkg/model/crd.go
scripts/lib/aws.sh
scripts/lib/aws/ecr.sh
scripts/lib/testutil.sh
services/ecr/generator.yaml
services/ecr/pkg/resource/repository/custom_update_api.go
services/ecr/pkg/resource/repository/sdk.go
templates/pkg/crd_sdk.go.tpl
test/e2e/ecr/smoke.sh

Some APIs, like ECR, have no Update operation at all for some resources
(like Repository). Instead, there are a series of API calls like
`PutImageScanningConfiguration`, `PutImageTagMutability`, or
`SetRepositoryPolicy` that set individual attributes for a particular
resource.
This patch adds the ability to override the implementation of
`sdkUpdate` **entirely** to a custom method name of the resourceManager
struct, thereby allowing total control over the various update
operations. This fixes a bug where, for the ECR sdk.go file, the
sdkUpdate method was empty and returning `(nil, nil)` which was causing
segfaults in the service controller.

allow total override of Update op

---

services/apigatewayv2/config/rbac/role.yaml
services/apigatewayv2/pkg/resource/api/manager.go
services/apigatewayv2/pkg/resource/api_mapping/manager.go
services/apigatewayv2/pkg/resource/authorizer/manager.go
services/apigatewayv2/pkg/resource/deployment/manager.go
services/apigatewayv2/pkg/resource/domain_name/manager.go
services/apigatewayv2/pkg/resource/integration/manager.go
services/apigatewayv2/pkg/resource/integration_response/manager.go
services/apigatewayv2/pkg/resource/model/manager.go
services/apigatewayv2/pkg/resource/route/manager.go
services/apigatewayv2/pkg/resource/route_response/manager.go
services/apigatewayv2/pkg/resource/stage/manager.go
services/apigatewayv2/pkg/resource/vpc_link/manager.go
services/ecr/config/rbac/role.yaml
services/ecr/pkg/resource/repository/manager.go
services/elasticache/config/rbac/role.yaml
services/elasticache/pkg/resource/cache_subnet_group/manager.go
services/elasticache/pkg/resource/replication_group/manager.go
services/s3/config/rbac/role.yaml
services/s3/pkg/resource/bucket/manager.go
services/sns/config/rbac/role.yaml
services/sns/pkg/resource/platform_application/manager.go
services/sns/pkg/resource/platform_endpoint/manager.go
services/sns/pkg/resource/topic/manager.go
templates/pkg/crd_manager.go.tpl
test/e2e/s3/cross-account.sh

Issue #353 
As per the description, I have updated the file with instruction for the controller-gen RBAC command to create the role permissions to allow reads from ConfigMap and Namespace resources. 
Also regenerated controller for following services. 
- s3
- sns
- apigatewayv2
- elasticache
- ecr

ACK service controllers RBAC issue fixed

---

.github/workflows/cleanup-self-hosted.yml

Instead of manually SSH'ing into self-hosted runners, allow users to
manually execute cleanup workflow to delete kind clusters on the runner.

Adds cleanup GH action workflow for hosted runners

---

.github/workflows/cleanup-self-hosted.yml

Apparently you cannot treat the `run:` part of GH action workflow's
steps as an actual shell. :(

remove hostnamectl from cleanup action

---

.github/workflows/cleanup-self-hosted.yml
scripts/install-kind.sh
scripts/lib/kind.sh

changes the way we install KinD to use binary install instead of `go
get`.

ensure kind is installed in cleanup

---

.github/workflows/build-unit-test.yaml
.github/workflows/e2e-test.yaml

Separates out the e2e test runs into a separate GH action workflow. Also
sets the max-parallel value for the e2e tests to 3, which is the number
of self-hosted runners we have, and allow the e2e workflow to be
manually triggered.

separate out e2e tests into new GH workflow

---

go.mod
pkg/metrics/metrics.go
pkg/runtime/reconciler.go
pkg/runtime/service_controller.go

Adds in a `pkg.metrics/Metrics` struct that contains a set of Prometheus
metric objects used to store data points for things we're interested in
tracking/instrumenting about the service controller's reconciler loop
and outbound AWS API calls.
Issue #355

add basic Metrics struct for recording API calls

---

scripts/lib/k8s.sh

We need to ensure that all ACK developers are using the same
controller-gen version otherwise we get into situations where:
1) go.mod/go.sum change unnecessarily
2) The annotations for things like CRDs will be different for generated
YAML manifests
This patch makes v0.4.0 of the controller-tools repo and controller-gen
binary our target version. It changes the `ensure_controller_gen` Bash
function to ensure that controller-gen at that version is installed and
refuses to proceed with building controllers if there is a different
version.
```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ controller-gen --version
Version: v0.3.1-0.20200716001835-4a903ddb7005
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ make build-controller SERVICE=dynamodb
make[1]: Entering …
```

align on controller-gen 0.4.0

---

.github/workflows/e2e-test.yaml

Something is causing the kind clusters to either be deleted or for the
e2e testing to be executed multiple times simulataneously on the
runners. Set the max-parallel to 1 to try and figure out what is being
hosed here...

force run e2e tests serially

---

.github/workflows/e2e-test.yaml

* Removes the unit testing from the e2e test by calling the
`scripts/kind-build-test.sh` script directly instead of
`make kind-test`
* Removes the preservation of the KinD cluster by removing the `-p`
argument from the call to `scripts/kind-build-test.sh`
* Builds the ack-generate and service controller in separate steps in
the e2e-test GH Actions workflow, allowing us to control these steps
separately.

control e2e test job more finely

---

services/README.md
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_apimappings.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_apis.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_authorizers.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_deployments.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_domainnames.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_integrationresponses.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_integrations.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_models.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_routeresponses.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_routes.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_stages.yaml
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_vpclinks.yaml
services/dynamodb/config/crd/bases/dynamodb.services.k8s.aws_backups.yaml
services/dynamodb/config/crd/bases/dynamodb.services.k8s.aws_globaltables.yaml
services/dynamodb/config/crd/bases/dynamodb.services.k8s.aws_tables.yaml
services/dynamodb/config/rbac/role.yaml
services/dynamodb/pkg/resource/backup/manager.go
services/dynamodb/pkg/resource/global_table/manager.go
services/dynamodb/pkg/resource/table/manager.go
services/ecr/config/crd/bases/ecr.services.k8s.aws_repositories.yaml
services/elasticache/config/crd/bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
services/elasticache/config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
services/readme.md
services/s3/config/crd/bases/s3.services.k8s.aws_buckets.yaml
services/sns/config/crd/bases/sns.services.k8s.aws_platformapplications.yaml
services/sns/config/crd/bases/sns.services.k8s.aws_platformendpoints.yaml
services/sns/config/crd/bases/sns.services.k8s.aws_topics.yaml

controller-gen 0.4.0 is now our standard build tooling and produces CRD
and Role files that are annotated with a specific version of the tool
that built them.
This patch simply updates all the service controllers to align with that
controller-gen 0.4.0 standard.
Fixes Issue #349

regenerate all controllers for c-g 0.4.0

---

services/elasticache/pkg/resource/replication_group/custom_update_api.go

Issue #377 
Updated the logic to compute the replica count as `NodeGroupMembers - 1` 

Replica count logic fix for Redis Cluster mode enabled

---

.github/workflows/build-unit-test.yaml
Makefile
scripts/install-mockery.sh

Modifies the `make` targets that create mocks to rely on installing
`mockery` v2.2.0 always into `bin/mockery`.

install mockery into bin/mockery always

---

.github/workflows/e2e-test.yaml

```
export AWS_ROLE_ARN=
./scripts/kind-build-test.sh -s $SERVICE -r $AWS_ROLE_ARN
shell: /usr/bin/bash -e {0}
env:
GOROOT: /home/ssm-user/actions-runner/_work/_tool/go/1.15.2/x64
SERVICE: s3
./scripts/kind-build-test.sh: option requires an argument -- r
```
Description of changes: 
- The GitHub secrets were not being passed as a `env` variable for forked repos
- Added `AWS_ROLE_ARN` and `AWS_ROLE_ARN_ALT` exports by reading the SSM parameters

Fixed the ENV variable error

---

CONTRIBUTING.md

Our open source program office has consulted with our legal folks and
determined that this mention of a CLA in our CONTRIBUTING docs was
neither necessary nor desired.

remove reference to CLA

---

pkg/compare/reporter.go
pkg/requeue/requeue.go
pkg/runtime/reconciler.go
scripts/lib/aws_elasticache_testutil.sh
services/apigatewayv2/pkg/resource/api/sdk.go
services/apigatewayv2/pkg/resource/api_mapping/sdk.go
services/apigatewayv2/pkg/resource/authorizer/sdk.go
services/apigatewayv2/pkg/resource/deployment/sdk.go
services/apigatewayv2/pkg/resource/domain_name/sdk.go
services/apigatewayv2/pkg/resource/integration/sdk.go
services/apigatewayv2/pkg/resource/integration_response/sdk.go
services/apigatewayv2/pkg/resource/model/sdk.go
services/apigatewayv2/pkg/resource/route/sdk.go
services/apigatewayv2/pkg/resource/route_response/sdk.go
services/apigatewayv2/pkg/resource/stage/sdk.go
services/apigatewayv2/pkg/resource/vpc_link/sdk.go
services/dynamodb/pkg/resource/backup/sdk.go
services/dynamodb/pkg/resource/global_table/sdk.go
services/dynamodb/pkg/resource/table/sdk.go
services/ecr/pkg/resource/repository/sdk.go
services/elasticache/pkg/resource/cache_subnet_group/sdk.go
services/elasticache/pkg/resource/replication_group/custom_set_output.go
services/elasticache/pkg/resource/replication_group/custom_update_api.go
services/elasticache/pkg/resource/replication_group/sdk.go
services/s3/pkg/resource/bucket/sdk.go
services/sns/pkg/resource/platform_application/sdk.go
services/sns/pkg/resource/platform_endpoint/sdk.go
services/sns/pkg/resource/topic/sdk.go
templates/pkg/crd_sdk.go.tpl

Issue #378 
* Added reconcile logic to Requeue after default interval (based on Conditions).
* Updated reconcile logic to updateCRStatus using already 'read' status (using ReadOne). This helps provide updated status to user when an ongoing operation takes long on remote service side and rm.update() fails due ongoing operation.
* Added logic to populate `OwnerAccountID` and `Conditions` inside sdkFind, as these is required in ko.Status
* Updated ElastiCache replicationgroup custom update method to check of available state in order to proceed.
* Updated ElastiCache replicationgroup custom output set method to populate `Conditions` with `ConditionTypeResourceSynced`
* Updated diff reporter to not include properties values. It lead to runtime errors when accessing …

Update status after Read operation and Requeue sync based on Conditions

---

.github/workflows/build-unit-test.yaml

Need to manually ensure controller-gen@v0.4.0 is installed for the unit test runners.

install controller-gen@v0.4.0 in unit test runner

---

.github/workflows/build-unit-test.yaml
.github/workflows/e2e-test.yaml

* allow build-unit-test to be manually triggered
* ONLY allow e2e-test to be manually triggered (for now... soon we will
set up an integration branch to run against on a periodic)

GH actions workflow changes

---

pkg/generate/generator.go
pkg/model/crd.go
pkg/model/crd_test.go

Issue N/A
- `replacePkgName` handle cases where `goType` is a nested slice or a nested map
- detach `replacePkgName` from `model.CRD` and change it signature
- Add unit tests for `replacePkgName`

`replacePkgName` handle cases of nested slices and nested maps

---

pkg/errors/error.go
pkg/runtime/reconciler.go
scripts/lib/aws/elasticache.sh
services/apigatewayv2/pkg/resource/api/sdk.go
services/apigatewayv2/pkg/resource/api_mapping/sdk.go
services/apigatewayv2/pkg/resource/authorizer/sdk.go
services/apigatewayv2/pkg/resource/deployment/sdk.go
services/apigatewayv2/pkg/resource/domain_name/sdk.go
services/apigatewayv2/pkg/resource/integration/sdk.go
services/apigatewayv2/pkg/resource/integration_response/sdk.go
services/apigatewayv2/pkg/resource/model/sdk.go
services/apigatewayv2/pkg/resource/route/sdk.go
services/apigatewayv2/pkg/resource/route_response/sdk.go
services/apigatewayv2/pkg/resource/stage/sdk.go
services/apigatewayv2/pkg/resource/vpc_link/sdk.go
services/dynamodb/pkg/resource/backup/sdk.go
services/dynamodb/pkg/resource/global_table/sdk.go
services/dynamodb/pkg/resource/table/sdk.go
services/ecr/pkg/resource/repository/sdk.go
services/elasticache/pkg/resource/cache_subnet_group/sdk.go
services/elasticache/pkg/resource/replication_group/custom_update_api.go
services/elasticache/pkg/resource/replication_group/sdk.go
services/s3/pkg/resource/bucket/sdk.go
services/sns/pkg/resource/platform_application/sdk.go
services/sns/pkg/resource/platform_endpoint/sdk.go
services/sns/pkg/resource/topic/sdk.go
templates/pkg/crd_sdk.go.tpl
test/e2e/elasticache/replication_group/e2e.sh

Issue #404 
* Fixed ReplicationGroup e2e test script
* Updated ReplicationGroup e2e test script wait logic
* Updated `replication_group/custom_update_api.go` to latest set output code.
* Added `TemporaryOutOfSync` error
* Added `setStatusDefaults` method and updated `sdk template` with it
* Updated sdkUpdate() call to invoke `setStatusDefaults()`
* Regenerated service controllers as sdk template got updated

Fix replication group e2e script, custom update, and use setStatusDefaults

---

pkg/names/names.go
pkg/names/names_test.go

Issue N/A
- Append an underscore to CRD names matching Go keywords
This was originally detected during the process of generating `es` (elastic search) service controller. "elastic search'' uses a data type named "package" which causes `ack-generate controller` to generate a Go package called "package". 
This PR will help preventing `ack-generate` from using Go keywords as CRD names.
For more details see [Elastic Search API](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-createpackage) or try to run `make build-controller SERVICE=es`

Append an underscore to CRD names matching Go keywords

---

scripts/lib/aws/elasticache.sh
scripts/lib/k8s.sh
test/e2e/elasticache/replication_group/e2e.sh

Renew credentials during e2e test.
`SERVICE=elasticache && make kind-test` ran the tests:
```
...
DEBUG: executing test: elasticache/smoke
...
DEBUG: Creating subnet group ack-test-smoke-elasticache-subnet-gp in elasticache
cachesubnetgroup.elasticache.services.k8s.aws/ack-test-smoke-elasticache-subnet-gp created
DEBUG: checking subnet group ack-test-smoke-elasticache-subnet-gp created in elasticache
DEBUG: Modifying subnet group ack-test-smoke-elasticache-subnet-gp in elasticache
cachesubnetgroup.elasticache.services.k8s.aws/ack-test-smoke-elasticache-subnet-gp configured
DEBUG: subnet group ack-test-smoke-elasticache-subnet-gp modified in elasticache
DEBUG: Deleting subnet group ack-test-smoke-elasticache-subnet-gp in elasticache …
```

renew credentials during e2e test

---

Dockerfile
pkg/runtime/reconciler.go
pkg/runtime/session.go
pkg/version/version.go

Issue #, if available: #409 
With this PR, we will inject session handler information/user-agent information while creating the session. 
Tested with debug logging:
```
Host: api.ecr.us-west-2.amazonaws.com
**User-Agent: aws-controller-k8s/0c76963-dirty (GitCommit/0c76963771053ea4310b5ffd0aaa399af0f88e87; BuildDate/2020-10-14T00:33:32+0000; Kind/Repository; CRDVersion/v1alpha1) aws-sdk-go/1.34.32 (go1.14.1; linux; amd64)
Content-Length: 72**
```

session handler info

---

scripts/build-controller.sh

Issue N/A
- Remove `check_is_installed docker` step from scripts/build-controller.sh

Remove `check_is_installed docker` step from scripts/build-controller.sh

---

docs/README.md
docs/mkdocs.yml

Description of changes: 
mkdocs-material api changed with version 6.0; updated mkdocs.yml to use new flag for navigation tabs; github action now builds site with navigation tabs; 
people can browse the docs site again! 

fix mkdocs config to enable tabs on docs site

---

pkg/generate/config/config.go
pkg/generate/sqs_test.go
pkg/generate/testdata/models/apis/sqs/0000-00-00/generator.yaml
pkg/model/crd.go
services/sqs/generator.yaml

The SQS GetQueueAttributes API call is entirely different from the SNS
GetTopicAttributes call. Whereas the latter is called and returns the
Topic's attributes, the former has a required `[]*string` field on the
Input shape called `AttributeNames` that has to have a single "All"
element in it in order for the API call not to return an error about
malformed Input data :(
This patch introduces new structures in the generator configuration that
allows the code generator to write override values for the Input shape
in order to populate this properly.
Issue #205

allow override of GetAttributes input shape

---

README.md

To ensure service terms are easy to locate for users of non-GA controllers.
* added language about use of non-GA controllers
* added link to AWS service terms

Update README with link to AWS preview terms

---

pkg/runtime/reconciler.go

Issue N/A
- Currently service controllers allow overriding the AWS Account ID by specifying a the `owner-account-id` annotation in the CR object. This commit disable this feature.  AWS Account ID should be specified in the annotations of the namespace in which the CR is created.

Ignore CRs `owner-account-id` annotation

---

pkg/errors/error.go
pkg/metrics/metrics.go
services/apigatewayv2/pkg/resource/api/sdk.go
services/apigatewayv2/pkg/resource/api_mapping/sdk.go
services/apigatewayv2/pkg/resource/authorizer/sdk.go
services/apigatewayv2/pkg/resource/deployment/sdk.go
services/apigatewayv2/pkg/resource/domain_name/sdk.go
services/apigatewayv2/pkg/resource/integration/sdk.go
services/apigatewayv2/pkg/resource/integration_response/sdk.go
services/apigatewayv2/pkg/resource/model/sdk.go
services/apigatewayv2/pkg/resource/route/sdk.go
services/apigatewayv2/pkg/resource/route_response/sdk.go
services/apigatewayv2/pkg/resource/stage/sdk.go
services/apigatewayv2/pkg/resource/vpc_link/sdk.go
services/dynamodb/pkg/resource/backup/sdk.go
services/dynamodb/pkg/resource/global_table/sdk.go
services/dynamodb/pkg/resource/table/sdk.go
services/ecr/pkg/resource/repository/sdk.go
services/elasticache/pkg/resource/cache_subnet_group/sdk.go
services/elasticache/pkg/resource/replication_group/sdk.go
services/s3/pkg/resource/bucket/sdk.go
services/sns/pkg/resource/platform_application/sdk.go
services/sns/pkg/resource/platform_endpoint/sdk.go
services/sns/pkg/resource/topic/sdk.go
templates/pkg/crd_sdk.go.tpl

Adds instrumentation into the sdk.go template to record API calls
made by the `resourceManager` against a backend AWS API. I left custom
update operations as an exercise for the reader...
Issue #355

instrument top-level AWS API call metrics

---

services/apigatewayv2/pkg/resource/api/manager.go
services/apigatewayv2/pkg/resource/api_mapping/manager.go
services/apigatewayv2/pkg/resource/authorizer/manager.go
services/apigatewayv2/pkg/resource/deployment/manager.go
services/apigatewayv2/pkg/resource/domain_name/manager.go
services/apigatewayv2/pkg/resource/integration/manager.go
services/apigatewayv2/pkg/resource/integration_response/manager.go
services/apigatewayv2/pkg/resource/model/manager.go
services/apigatewayv2/pkg/resource/route/manager.go
services/apigatewayv2/pkg/resource/route_response/manager.go
services/apigatewayv2/pkg/resource/stage/manager.go
services/apigatewayv2/pkg/resource/vpc_link/manager.go
services/dynamodb/pkg/resource/backup/manager.go
services/dynamodb/pkg/resource/global_table/manager.go
services/dynamodb/pkg/resource/table/manager.go
services/ecr/pkg/resource/repository/manager.go
services/elasticache/pkg/resource/cache_subnet_group/manager.go
services/elasticache/pkg/resource/replication_group/manager.go
services/s3/pkg/resource/bucket/manager.go
services/sns/pkg/resource/platform_application/manager.go
services/sns/pkg/resource/platform_endpoint/manager.go
services/sns/pkg/resource/topic/manager.go
templates/pkg/crd_manager.go.tpl

Issue #427 
Changed the return type of onError and onSuccess methods from:
`(*resource, error)` to `(acktypes.AWSResource, error)` for nil check to work inside reconciler.
Inside reconciler, the value is received into `var latest acktypes.AWSResource` 
and it failed to have the expected execution of 
```
if latest != nil {
```
condition when manager.go `onError()` method return `nil`.
Changing the return type to `(acktypes.AWSResource, error)` resolves the issue.

Fix nil pointer dereference inside reconciler when manager onError returns nil

---

services/elasticache/pkg/resource/replication_group/custom_update_api.go

Issue #413 
Code updates to compare the multi az enabled, auto failover enabled from Spec with the values from Status.
Also the values from Status are not boolean, thus determined true/false values based on string comparison. 

Replication Group multi az and auto failover status values handling during update

---

pkg/generate/template.go
services/dynamodb/pkg/resource/backup/sdk.go
services/s3/pkg/resource/bucket/sdk.go
services/sns/pkg/resource/platform_endpoint/sdk.go
templates/pkg/resource/sdk.go.tpl
templates/pkg/resource/sdk_update.go.tpl
templates/pkg/resource/sdk_update_custom.go.tpl
templates/pkg/resource/sdk_update_not_implemented.go.tpl
templates/pkg/resource/sdk_update_set_attributes.go.tpl

continues the cleanup of the top-level sdk.go.tpl template file by
breaking the sdkUpdate implementation for "normal" Update, custom
update, and SetAttributes update code paths into separate sub-templates.

break out sdkUpdate into sep templates

---

docs/contents/dev-docs/testing.md
docs/contents/services.md
services/elasticache/README.md

The ACK service controller for Amazon ElastiCache supports the following Amazon ElastiCache API resources in `DEVELOPER PREVIEW`:
Updated md files and added README file.

place elasticache service controller into dev-preview

---

templates/pkg/resource/sdk_find_read_one.go.tpl

Issue #, if available: https://github.com/aws/aws-controllers-k8s/issues/451
Description of changes: Fix a somewhat minor bug. This error handling block is checking one error variable, but returning an unrelated one. The unrelated one is nil and will cause seg faults elsewhere.

Fix incorrect error returned from sdkFind()

---

cmd/ack-generate/command/apis.go
cmd/ack-generate/command/controller.go
pkg/generate/config/config.go
pkg/generate/ecr_test.go
pkg/generate/elasticache_test.go
pkg/generate/generator.go
pkg/generate/rds_test.go
pkg/generate/s3_test.go
pkg/model/crd.go
pkg/model/sdk_helper.go
pkg/testutil/schema_helper.go

Description of changes: As part of the ongoing [effort](https://github.com/crossplane/crossplane/issues/1845) about generating Crossplane AWS Provider, there are some small changes where ACK and Crossplane patterns diverge. In CP, we have all the provider-related fields under `spec.forProvider` so that it's separate from CP machinery fields. Same with status, we have `status.atProvider` to differentiate them from other fields. For details, you can see [Managed Resources API Patterns Design Doc](https://github.com/crossplane/crossplane/blob/37013c6/design/one-pager-managed-resource-api-design.md).
I tried to make the change as least intrusive as possible to the existing mechanisms. Please let me know if you think it could be done in a better way.
By submitting this pull request, I confirm …

Additional fields with defaults to generate.Config object

---

scripts/kind-build-test.sh

N/A
Fix parameter inputs in `kind-build-test.sh`

kind-build-test.sh add colons in getopts for -i and -v

---

scripts/lib/aws.sh
scripts/lib/aws/apigatewayv2.sh

Issue #394 , if available:
* Making daws use local file system for aws commands that need to upload file. Assuming this won't harm any other e2e test
* Adding prechecks in resource setup for apigwv2 e2e tests.
* I know we are using awscliv2 now but still checking exit status for both 255 & 254 for NotFoundExceptions.
```
vijat@186590cff3cf aws-controllers-k8s % ./scripts/kind-build-test.sh -s apigatewayv2 -p -r arn:aws:iam::309117047740:role/Admin-k8s -c /Users/vijat/Documents/gocode/src/github.com/vijtrip2/aws-controllers-k8s/scripts/lib/../../build/tmp-ack-test-5765e6b8-68b12ea9
checking AWS credentials ... ok.
building ack-apigatewayv2-controller docker image ... ok.
loading the images into the cluster ... ok.
loading CRD manifests for apigatewayv2 into the …
```

Add prechecks in apigwv2 e2e tests.

---

pkg/generate/config/config.go
pkg/model/crd.go
templates/pkg/resource/descriptor.go.tpl

Issue N/A
- Adding `Compare` field to the generator configuration, to support custom comparison logic for CR objects.
- Adding `Ignore` field to the Compare configuration, to instruct the generator to ignore certain fields when comparing two different CRs
Configuration example:
```yaml
resources:
Function:
exceptions:
codes:
404: ResourceNotFoundException
list_operation:
match_fields:
- FunctionName
compare:
ignore:
- 'Spec.Code.s3Bucket'
- 'Spec.Code.s3Key'
- 'Status.Code.Location'
- 'Status.Code.Type'
```

Add `compare` configuration to support ignoring specific fields when comparing CRs

---

templates/pkg/resource/descriptor.go.tpl

Issue N/A, followup to: #465 
While debugging the lambda controller i found an issue regarding `cmpopts.IgnoreFields` usage (oops 😄 )
Fix `cmpopts` usage by passing a struct value sample to `cmpopts.IgnoreFields` instead of a value pointer

Pass a struct value sample to `cmpopts.IgnoreFields` instead of a value pointer

---

cmd/ack-generate/command/controller.go
cmd/ack-generate/command/release.go
docs/contents/dev-docs/release.md
pkg/generate/template.go
scripts/build-controller-release.sh
scripts/install-helm.sh
scripts/kind-build-test.sh
scripts/lib/helm.sh
templates/helm/Chart.yaml.tpl
templates/helm/templates/_helpers.tpl
templates/helm/templates/cluster-role-binding.yaml
templates/helm/templates/deployment.yaml
templates/helm/values.yaml.tpl
test/release/test-helm.sh

Adds a new `ack-generate release <SERVICE> <VERSION>` command that
generates a Helm chart for a specific service controller and release
version combination.
The Helm chart that is generated installs the Docker image for the
ACK controller for that service and release version. For example, if you
run:
```bash
ack-generate release s3 v0.0.1
```
the Helm chart generated will be placed in
`/services/s3/helm/Chart.yaml` and the image referred to from the
Deployment created in that chart will be
`amazon/aws-controllers-k8s:s3-v0.0.1`.
Also includes documentation on the release steps and a test of the Helm
installation process.
Issue #366 
Issue #456 

add `ack-generate release` command

---

templates/helm/templates/cluster-role-binding.yaml
templates/helm/templates/deployment.yaml

- Add service account name for controller deployment pod specs
- Use `app.name` instead of `app.fullname` for ClusterRole refName
Issue #366 

Fix ClusterRole ref name in cluster-role-binding.yml

---

docs/contents/user-docs/install.md
scripts/build-controller-release.sh
scripts/helm-package-controller.sh
scripts/publish-controller-image.sh

Updates the user installation docs to better highlight the way our
Docker images are tagged and how to properly install with Helm.
Adds a new `scripts/helm-package-controller.sh` script that runs the
`helm package` command against a service controller's generated Helm
chart to create the tarball package that is needed to place in the Helm
repository we'll be indexing in our gh-pages branch of the
aws-controllers-k8s source repository.
Issue #366 

update install docs and add helm package script

---

scripts/build-controller-release.sh

Issue #366
- Use service related names for `ServiceAccount` k8s resource naming

Use service related names for ServiceAccount names in ./scripts/build-controller-release.sh

---

scripts/helm-publish-charts.sh

Adds a new script that builds all the Helm packages for all service
controllers, builds the Helm repository index.yaml and, optionally, git
commits the resulting charts and Helm repository files into the
`gh-pages` Git branch of the upstream source repository, which allows us
to publish our Helm repository for ACK service controllers on our
Github Pages redirect.
```
jaypipes@thelio:~/go/src/github.com/aws/aws-controllers-k8s$ ./scripts/helm-publish-charts.sh
Generating Helm chart package for apigatewayv2 ... ok.
Generating Helm chart package for dynamodb ... ok.
Generating Helm chart package for ecr ... ok.
Generating Helm chart package for elasticache ... ok.
Generating Helm chart package for s3 ... ok.
Generating Helm chart package for sfn ... ok.
Generating Helm chart package for sns …
```

add script to publish Helm charts

---

docs/contents/user-docs/install.md

Thanks to @muvaf for pointing out that the Helm repo URL was incorrect
and that the `helm install` command needs a name for the Helm release.

Fix Helm install instructions

---

cmd/ack-generate/command/controller.go
pkg/generate/template.go
templates/config/crd/kustomization.yaml.tpl
templates/config/default/kustomization.yaml.tpl

Closes #468
Related to https://github.com/aws/aws-controllers-k8s/pull/469
`ack-generate` now creates a `kustomization.yaml` in `${SERVICE}/config/crd` with all the crds manifests under `crd/bases`.
Now running `kustomize build services/${SERVICE}/config/default` will render crds.
Re-running `ack-generate` for all services will be required and makes https://github.com/aws/aws-controllers-k8s/pull/469 unnecessary.

Generate kustomization for crds

---

scripts/lib/aws/sns.sh
test/e2e/sns/cross-region.sh

Issue #81
- Add AWS_REGION and AWS_PROFILE arguments to `sns_topic_exists`
- Add `sns/cross-region.sh` script to test cross region feature

Add cross region resource management smoke tests

---

docs/contents/user-docs/authorization.md
docs/contents/user-docs/irsa.md
pkg/generate/template.go
scripts/build-controller-release.sh
scripts/build-controller.sh
scripts/install-helm.sh
templates/config/rbac/cluster-role-binding.yaml.tpl
templates/config/rbac/kustomization.yaml.tpl
templates/config/rbac/role-reader.yaml.tpl
templates/config/rbac/role-writer.yaml.tpl
templates/helm/templates/role-reader.yaml.tpl
templates/helm/templates/role-writer.yaml.tpl

Our documentation mentions standardized Roles called
`ack-$SERVICE-reader` and `ack-$SERVICE-writer` that can be bound to
users in order to give them read or read/write permissions to operate on
CRDs of a particular service controller.
However, until this PR, we weren't actually generating these Roles. This
PR adds the generation of those standardized Role resources and modifies
the documentation for configuring Kubernetes RoleBindings to match the
`ack-$SERVICE-reader` and `ack-$SERVICE-writer` Roles we are now
producing.
Issue #366 

Generate ack-$SERVICE-[reader|writer] Roles

---

scripts/lib/aws/elasticache.sh
services/elasticache/pkg/resource/cache_parameter_group/custom_update_api.go
test/e2e/elasticache/cache_parameter_group/e2e.sh

Issue #457 
Issue #262 
Description of changes: e2e tests for CacheParameterGroup API for ElastiCache controller.
tests include:
- Create CacheParameterGroup
- Update CacheParameterGroup by adding custom (user) cache parameters
- Update CacheParameterGroup by updating custom cache paramters
- Update CacheParameterGroup by removing some custom cache parameters (by removing from yaml, by setting value to "")
- Reset all custom cache parameters of CacheParameterGroup
- Delete CacheParameterGroup
Test run output:
```
$ e2e/elasticache/cache_parameter_group/e2e.sh
DEBUG: executing test: elasticache/e2e
DEBUG: Testing create Cache Parameter Group: ack-test-cpg-2.
cacheparametergroup.elasticache.services.k8s.aws/ack-test-cpg-2 created
DEBUG: Testing modify Cache Parameter Group: ack-test-cpg-2. …
```

CacheParameterGroup e2e test

---

services/dynamodb/generator.yaml
services/dynamodb/pkg/resource/backup/sdk.go
services/dynamodb/pkg/resource/global_table/sdk.go

Description of changes: While generating [DynamoDB services for Crossplane](https://github.com/crossplane/provider-aws/pull/446), I have discovered that they need custom 404 exception codes similar to ECR.

dynamodb: add custom 404 exception codes for GlobalTable and Backup

---

pkg/generate/config/config.go
pkg/generate/generator.go
pkg/generate/rds_test.go
pkg/model/crd.go
pkg/model/sdk_helper.go

Description of changes: This PR adds a new ignore rule to `Config` object where users can define which specific field they want to ignore, like `CreateApiInput.Name`. It also moves the shape ignore rule to the same function that is run only once during the beginning.
Tested this with APIGatewayv2 resources generated [here](https://github.com/crossplane/provider-aws/pull/416).
This is necessary for Crossplane code generation where we need to ignore the field we use [external-name annotation](https://crossplane.io/docs/v0.14/introduction/managed-resources.html#external-name) for and the fields that are required but could be referenced; those fields should be marked as non-required since they could be fulfilled by the controller after reference resolution. For the referenced fields, we could …

Add FieldPaths to ignore rules

---

scripts/delete-kind-cluster.sh
scripts/kind-build-test.sh

Refactoring stage: Argument variable values as env variables instead of getops strategy
Script: delete-kind-cluster.sh
Replaced getopts strategy with a fixed number of arguments (cluster context path ) and env variable (override binary path, defaulted to 0). Fixed references to this script in kind-build-test.sh

removed getopts strategy from delete-kind-cluster

---

scripts/lib/aws/elasticache.sh
test/e2e/elasticache/replication_group/creation.sh
test/e2e/elasticache/replication_group/e2e.sh
test/e2e/elasticache/replication_group/misc.sh
test/e2e/elasticache/replication_group/replication.sh
test/e2e/elasticache/replication_group/scaling.sh
test/e2e/elasticache/snapshot/e2e.sh

Enhancement of existing Elasticache e2e tests, mainly adding tests for Snapshot and fixing ROOT_DIR for replication group tests (files were moved out of a subdirectory in the last PR)
Questions:
- additional cases needed for subnet group?
- how to give KMS access to IAM role for test_snapshot_create_KMS test?

Elasticache e2e test enhancement

---

services/elasticache/apis/v1alpha1/replication_group.go
services/elasticache/apis/v1alpha1/zz_generated.deepcopy.go
services/elasticache/config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
services/elasticache/generator.yaml
services/elasticache/pkg/resource/replication_group/custom_set_output.go

Add allowed node modifications to the status of replication group.
`kubectl describe` will have the status if RG is in active or snapshotting status.
```
Pending Modified Values:
Scale Down Modifications:
cache.t2.micro
cache.t3.micro
Scale Up Modifications:
cache.m4.10xlarge
cache.m4.2xlarge
cache.m4.4xlarge
cache.m4.large
cache.m4.xlarge
cache.m5.12xlarge
cache.m5.24xlarge
cache.m5.2xlarge
cache.m5.4xlarge
cache.m5.large
cache.m5.xlarge
cache.m6g.large
cache.r4.2xlarge
cache.r4.4xlarge
cache.r4.8xlarge
cache.r4.large
cache.r4.xlarge
cache.r5.12xlarge
cache.r5.24xlarge
cache.r5.2xlarge
cache.r5.4xlarge
cache.r5.large
cache.r5.xlarge
cache.r6g.large
cache.t2.medium
cache.t2.small
cache.t3.medium
Status:  available
Events:    <none>
```
Removed this field while modifying as it might not be …

Support for ListAllowedNodeTypeModifications

---

scripts/lib/aws/apigatewayv2.sh
test/e2e/apigatewayv2/api/e2e.sh

Issue #539 :
Adding update-api into apigatewayv2 e2e test
```
vijat@186590cff3cf aws-controllers-k8s % make build-ack-generate                                                                    
building ack-generate ... ok.
vijat@186590cff3cf aws-controllers-k8s % ./scripts/kind-build-test.sh -s apigatewayv2 -p -r arn:aws:iam::309117047740:role/Admin-k8s
checking AWS credentials ... ok.
creating kind cluster ack-test-e5508ed3-76898c79 ... ok.
[+] Building 209.7s (15/15) FINISHED                                                                                                       
=> [internal] load build definition from Dockerfile                                                                                  0.8s
=> => transferring dockerfile: 39B …
```

Adding update-api operation in apigatewayv2 e2e test.

---

pkg/runtime/reconciler.go
services/apigatewayv2/pkg/resource/api/manager.go
services/apigatewayv2/pkg/resource/api_mapping/manager.go
services/apigatewayv2/pkg/resource/authorizer/manager.go
services/apigatewayv2/pkg/resource/deployment/manager.go
services/apigatewayv2/pkg/resource/domain_name/manager.go
services/apigatewayv2/pkg/resource/integration/manager.go
services/apigatewayv2/pkg/resource/integration_response/manager.go
services/apigatewayv2/pkg/resource/model/manager.go
services/apigatewayv2/pkg/resource/route/manager.go
services/apigatewayv2/pkg/resource/route_response/manager.go
services/apigatewayv2/pkg/resource/stage/manager.go
services/apigatewayv2/pkg/resource/vpc_link/manager.go
services/dynamodb/pkg/resource/backup/manager.go
services/dynamodb/pkg/resource/global_table/manager.go
services/dynamodb/pkg/resource/table/manager.go
services/ecr/pkg/resource/repository/manager.go
services/elasticache/pkg/resource/cache_parameter_group/custom_update_api.go
services/elasticache/pkg/resource/cache_parameter_group/manager.go
services/elasticache/pkg/resource/cache_subnet_group/manager.go
services/elasticache/pkg/resource/replication_group/manager.go
services/elasticache/pkg/resource/snapshot/manager.go
services/s3/pkg/resource/bucket/manager.go
services/sagemaker/pkg/resource/model/manager.go
services/sfn/pkg/resource/activity/manager.go
services/sfn/pkg/resource/state_machine/manager.go
services/sns/pkg/resource/platform_application/manager.go
services/sns/pkg/resource/platform_endpoint/manager.go
services/sns/pkg/resource/topic/manager.go
templates/pkg/resource/manager.go.tpl

Issue #494 
The changes fix the issue where Terminal condition fluctuates between a `false` and `true` value
Steps to reproduce:
The issue occurs when a custom resource was successfully reconciled and its terminal condition is false or not set.
Then if this resource is updated using yaml which would result in failure during modify call; then this issue surfaces.
Cause:
`rm.ReadOne()` for already created resource returns successfully; the code which invokes `patchResource()` before the `rm.Update()` call sets the terminal condition to `false` (because of successful retrieval of `latest` object not having any failure); this is followed by `rm.Update()` call which fails with terminal condition and results in setting it to `true`.
Fix:
- The call to `patchResource()` …

Terminal Condition stabilization

---

pkg/generate/elasticache_test.go
pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
services/elasticache/apis/v1alpha1/cache_parameter_group.go
services/elasticache/apis/v1alpha1/cache_subnet_group.go
services/elasticache/apis/v1alpha1/replication_group.go
services/elasticache/apis/v1alpha1/zz_generated.deepcopy.go
services/elasticache/config/crd/bases/elasticache.services.k8s.aws_cacheparametergroups.yaml
services/elasticache/config/crd/bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
services/elasticache/config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
services/elasticache/generator.yaml
services/elasticache/pkg/resource/cache_parameter_group/custom_api.go
services/elasticache/pkg/resource/cache_subnet_group/custom_set_output.go
services/elasticache/pkg/resource/cache_subnet_group/sdk.go
services/elasticache/pkg/resource/replication_group/custom_set_output.go

Issue #527 
ElastiCache DescribeEvents support for:
- Replication Group,
- Cache Parameter Group,
- Cache Subnet Group
Example Events for replication group `kubectl` get call:
```
"events": [
{
"date": "2020-11-25T06:42:57Z",
"message": "Moved a total of 8192 slots out of 8192 slots from shard 0004 to shard 0001"
},
{
"date": "2020-11-25T06:36:51Z",
"message": "Migrating slots from node groups 0004 to 0001 to rebalance slots"
},
{
"date": "2020-11-25T06:34:41Z",
"message": "Modified replication group ack-test-rg-1 to add 1 new node groups - 0001"
},
{
"date": "2020-11-25T06:25:00Z",
"message": "Scaling out replication group ack-test-rg-1 from 1 node groups to 2 node groups"
},
{
"date": "2020-11-25T06:24:08Z",
"message": "Increase replica count completed for …
```

ElastiCache DescribeEvents support

---

scripts/publish-controller-image.sh

Refactoring stage: Argument variable values as env variables instead of getopts strategy
Script: publish-controller-image.sh
Replaced getopts strategy with a fixed number of arguments (aws service name ) and env variables.

removed getopts strategy from publish-controller-image.sh

---

Makefile
scripts/lib/aws/elasticache.sh
scripts/lib/testutil.sh
test/e2e/elasticache/replication_group/creation.sh
test/e2e/elasticache/replication_group/e2e.sh
test/e2e/elasticache/replication_group/misc.sh
test/e2e/elasticache/replication_group/replication.sh
test/e2e/elasticache/replication_group/scaling.sh
test/e2e/elasticache/snapshot/e2e.sh

https://github.com/aws/aws-controllers-k8s/issues/494
Related PRs:
https://github.com/aws/aws-controllers-k8s/pull/531
https://github.com/aws/aws-controllers-k8s/pull/530
- Moved some generic resource testing functions to testutil.sh as requested in pull 528
- Verified terminal condition stabilization fix, issue 494/PR 531
- Changed the wait function (for replication groups) to wait on ResourceSynced condition rather than status.status property to properly test this
- Improved test output (added output for wait loop and no longer suppressing kubectl apply output), was previously hard see what was going on in each test
- Re-added some extra tests that were saved on a local branch
- Updated kind-test target in Makefile (old target was broken …

Elasticache e2e tests: verification, more tests, cleanup

---

pkg/generate/config/config.go
pkg/generate/elasticache_test.go
pkg/generate/generator.go
pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
pkg/model/crd.go
services/elasticache/apis/v1alpha1/replication_group.go
services/elasticache/apis/v1alpha1/zz_generated.deepcopy.go
services/elasticache/config/crd/bases/elasticache.services.k8s.aws_replicationgroups.yaml
services/elasticache/generator.yaml
services/elasticache/pkg/resource/replication_group/custom_set_output.go

Added ability to rename the additional Status and Spec field.
For ElastiCache, updated status from ScaleUpModifications to AllowedScaleUpModifications.
```
Allowed Scale Up Modifications:
cache.m4.10xlarge
cache.m4.2xlarge
cache.m4.4xlarge
cache.m4.large
cache.m4.xlarge
cache.m5.12xlarge
cache.m5.24xlarge
```

Rename Status and Spec Field

---

.github/workflows/e2e-test.yaml

When we merged the fixes to kind-build-test.sh we forgot to update the
execution in the workflow to remove the CLI args and replace with
params.

fix e2e execution in GH workflow

---

services/elasticache/pkg/resource/cache_parameter_group/manager.go
services/elasticache/pkg/resource/cache_subnet_group/manager.go
services/elasticache/pkg/resource/replication_group/manager.go
services/elasticache/pkg/resource/snapshot/manager.go
templates/pkg/resource/manager.go.tpl

InvalidParameterCombination exception can be thrown for Elasticache snapshot find. This results in endless exceptions and no status change in `kubectl get or describe`
After the change terminal condition is set.
```
"conditions": [
{
"message": "Cannot specify both ReplicationGroupId and CacheClusterId",
"status": "True",
"type": "ACK.Terminal"
}
]
```

Update terminal conditions for SDK Find

---

.github/workflows/e2e-test.yaml

I goofed in #572. There should only be a single parameter passed to the
kind-build-test.sh script.

fix e2e workflow to only pass one arg

---

scripts/kind-build-test.sh
scripts/provision-kind-cluster.sh

Refactoring stage: Argument variable values as env variables instead of getopts strategy
Script: provision-kind-cluster.sh
- Replaced getopts strategy with a fixed number of arguments and env variables.
- Removed unused variable OVERRIDE_PATH.
- Fixed reference to this script from kind-build-test.sh.

rm getopts strategy from provision-kind-cluster.sh

---

scripts/lib/aws.sh

pass the `z` flag to the docker volume for the AWS credentials when
launching aws-cli Docker image in `daws` script utility.
On Fedora/RHEL systems, this is necessary otherwise the aws-cli in the
Docker image won't be able to read the .aws credentials directory
properly.
ref: https://github.com/aws/aws-cli/issues/5811
ref: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

pass selinux labels to docker mount in daws

---

pkg/runtime/reconciler.go
services/elasticache/pkg/resource/snapshot/custom_update_api.go
test/e2e/elasticache/snapshot/e2e.sh

Fixes for Snapshot failures:
```
1. Fix snapshot crud failures:
Cause: update did not save the sync status condition
Fix: update() needed to return latest retrieved.
2. Fix endless reconciler loop:
Cause: ReadOne->onError() sets terminal condition to false using patchResource,
followed by error returned from Create() leads to
setting terminal condition to true using patchResource;
causing reconciler loop.
Fix: ensure patchResource is invoked once in the reconciler::sync()
3 Snapshots e2e tests fix - updated scenarios where create snapshot expects either Replication Group or Cache Cluster Id and fails if other is supplied.
```
Testing done:
```
1. Snapshot e2e tests passed.
2. apigatewayv2 e2e tests passed.
```
By submitting this pull request, …

Fixes for Snapshot failures

---

docs/contents/dev-docs/release.md
docs/contents/user-docs/install.md
scripts/build-controller-release.sh
scripts/helm-publish-charts.sh
services/apigatewayv2/helm/values.yaml
services/dynamodb/helm/values.yaml
services/ecr/helm/values.yaml
services/elasticache/helm/values.yaml
services/s3/helm/values.yaml
services/sfn/helm/values.yaml
services/sns/helm/values.yaml

Modifies our release docs and publish scripts to use our new ECR public
registry (public.ecr.aws/aws-controllers-k8s) for storing Docker images
for the controllers and Helm charts.
Note that the public alias "public.ecr.aws/aws-controllers-k8s" is still
not resolving from the generated alias of "public.ecr.aws/m5q3e4b2" but
that should be done shortly by the ECR team.
Issue #366

update release and publish scripts for ECR

---

templates/crossplane/apis/crd.go.tpl
templates/crossplane/pkg/controller.go.tpl

Description of changes: There is a breaking change in [latest crossplane-runtime](https://github.com/crossplane/crossplane-runtime/releases/tag/v0.12.0) that necessitates changes of these import paths.

Update crossplane-runtime import paths to match latest release

---

pkg/generate/config/field.go
pkg/generate/generator.go
pkg/model/crd.go
services/sagemaker/generator.yaml
templates/apis/crd.go.tpl

Issue #, if available: #561 
Adds support for "AdditionalPrinterColumns" (generated by `controller-gen`).
Both status and spec fields in the `generator.yaml` file now have an additional `printable_column` boolean. If enabled, the generator will add the target field as a printable column annotation.
Please give me feedback on how best to map the golang field types to OpenAPI data types - this may already be elsewhere in the code that I was unable to find.

Generate printer columns for service controller CRDs

---

pkg/generate/ack/release.go

The TemplateSet for ACK's release artifacts was improperly including the
`.tpl` extension in the outputPath. This patch simply corrects that
outputPath to remove the `.tpl` suffix.

specify outPath without .tpl extension for release

---

pkg/generate/apigwv2_test.go
pkg/generate/config/field.go
pkg/generate/testdata/models/apis/apigatewayv2/0000-00-00/generator.yaml
pkg/model/crd.go
scripts/kind-build-test.sh
scripts/lib/aws/apigatewayv2.sh
scripts/lib/common.sh
services/apigatewayv2/apis/v1alpha1/api.go
services/apigatewayv2/apis/v1alpha1/zz_generated.deepcopy.go
services/apigatewayv2/config/crd/bases/apigatewayv2.services.k8s.aws_apis.yaml
services/apigatewayv2/generator.yaml
services/apigatewayv2/helm/crds/apigatewayv2.services.k8s.aws_apis.yaml
services/apigatewayv2/pkg/resource/api/custom_http_api.go
services/apigatewayv2/pkg/resource/api/custom_http_api_test.go
services/apigatewayv2/pkg/resource/api/sdk.go
test/e2e/apigatewayv2/api/e2e.sh
test/e2e/run-tests.sh

Issue #128 , if available:
Same as PR #600 but squashed into single commit.
* **Fixing the classic e2e test run. Temporarily commenting docker test run.**
* Update ack-generate/release to drop ".tpl" from files generated for helm charts.
* I spent one day trying to fix docker-file and scripts for successfully running docker-test-run but in the end I hit the blocker where daws was unable to run inside docker.
* Then I fall back to old e2e runs and temporarily commented docker-test-runs from kind-build-test
* I made some minor fixes in script for successfully running e2e tests. 
* **Adding required override for fields in FieldConfig.**
* Introduced a new boolean field 'IsRequired' in FieldConfig to override the required behavior present in …

Implementing ImportApi & ReimportApi for apigatewayv2.

---

scripts/build-controller-image.sh
scripts/build-controller-release.sh
scripts/build-controller.sh
scripts/delete-kind-cluster.sh
scripts/helm-package-controller.sh
scripts/helm-publish-charts.sh
scripts/install-controller-gen.sh
scripts/install-helm.sh
scripts/install-kind.sh
scripts/install-kubectl.sh
scripts/install-kustomize.sh
scripts/install-mockery.sh
scripts/kind-build-test.sh
scripts/provision-kind-cluster.sh
scripts/publish-controller-image.sh

Issue #504 
Standardize how the current directory is determined. Between the varied methods used, I have chosen the following:
`THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"`
Reasons:
- It now matches how it's done in other folders like `/test`
- it works even if the scripts are sourced, `dirname $0` will point to the bash binary when sourced instead. E.g.:
```
[nnosenzo@localhost aws-controllers-k8s]$ cat test.sh 
#!/usr/bin/env bash
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
echo $THIS_DIR
SCRIPTS_DIR=$(cd "$(dirname "$0")"; pwd)
echo $SCRIPTS_DIR
```
Then, 
```
[nnosenzo@localhost aws-controllers-k8s]$ ./test.sh 
/home/nnosenzo/go/src/github.com/niconosenzo/aws-controllers-k8s …
```

standardize how current directory is determined

---

docs/contents/dev-docs/api-inference.md

Adds documentation that describes the process by which we infer API type
definitions for ACK service controllers, including explanation of how a
"resource" is identified and how we determine the structure of the
`Spec` and `Status` fields on a CR.

add docs on how we generate CR definitions

---

docs/contents/dev-docs/testing.md
scripts/install-controller-gen.sh

Updated install-controller-gen.sh to use GO Binary to determine
GOPATH as not all platforms have $GOPATH configured. Updated dev docs
to supported version of GO based on go.mod file.
* Update docs for clarity
* Update install-controller-gen.sh to support different platforms by using go binary to find the environment path

Update install-controller-gen.sh and dev docs

---

scripts/lib/aws/elasticache.sh
test/e2e/elasticache/cache_parameter_group/e2e.sh
test/e2e/elasticache/replication_group/creation.sh

Add new asserts for the existing tests to validate events, allowed node modifications.
Asserting on exact  allowed node type modifications and events is difficult so we assert on length.

E2E Tests for Events, Allowed node modifications

---

scripts/lib/aws/elasticache.sh
scripts/lib/testutil.sh
services/elasticache/generator.yaml
services/elasticache/pkg/resource/cache_parameter_group/custom_api.go
services/elasticache/pkg/resource/cache_subnet_group/custom_set_output.go
services/elasticache/pkg/resource/cache_subnet_group/sdk.go
services/elasticache/pkg/resource/replication_group/custom_set_output.go
services/elasticache/pkg/resource/replication_group/custom_update_api.go
services/elasticache/pkg/resource/replication_group/custom_update_api_test.go
services/elasticache/pkg/resource/replication_group/sdk.go
test/e2e/elasticache/replication_group/creation.sh
test/e2e/elasticache/replication_group/misc.sh
test/e2e/elasticache/replication_group/replication.sh
test/e2e/elasticache/replication_group/scaling.sh
test/e2e/elasticache/snapshot/e2e.sh

- Fix credential expire issue during elasticache tests failures. This caused the controller to fail to get the latest details from service API and the test would timeout waiting for latest updates.
- Fixes for replication group tests failures by
- Include security group Ids and engine versions properties
in modify replication group API call
only if there is change in their values
- Updated sync condition logic to: 
a/ check all cache clusters' available status from node groups and 
b/ check if the cacheclusters count from node groups match the count from member clusters
- Added logs messages to help debugging
- Updated replication group tests that were failing due to invalid input yaml
- Added cache subnet group terminal codes in generator …

Fix replication group tests failures

---

scripts/kind-build-test.sh
test/e2e/README.md
test/e2e/build-run-test-dockerfile.sh
test/e2e/run-tests.sh

Attempting to fix automation of integration tests, don't want shell script tests to use Dockerfile.

Fix integration test automation

---

kind-setup/prometheus/prometheus-setup.yaml
pkg/generate/ack/controller.go
scripts/kind-build-test.sh
scripts/kind-two-node-cluster.yaml
scripts/lib/k8s.sh
services/elasticache/config/controller/deployment.yaml
services/elasticache/config/controller/kustomization.yaml
services/elasticache/config/controller/service.yaml
templates/config/controller/deployment.yaml.tpl
templates/config/controller/kustomization.yaml.tpl
templates/config/controller/service.yaml.tpl
templates/helm/templates/deployment.yaml
templates/helm/values.yaml.tpl

* Adds container ports in deployment files for metrics discovery
* Option to setup prometheus during kind-test (default false):
Use with `make kind-test`:
```
ENABLE_PROMETHEUS=true make kind-test
```
Upon setup, the prometheus URL (http://localhost:9090) can be accessed on host machine.

option to setup prometheus during kind-test

---

docs/contents/services.md

Updates the service release matrix and docs to the latest status and
adds ACM, Kinesis, KSM, EC2 VPC service controllers in Proposed status.

refresh service release docs

---

services/sagemaker/apis/v1alpha1/training_job.go
services/sagemaker/apis/v1alpha1/zz_generated.deepcopy.go
services/sagemaker/config/controller/deployment.yaml
services/sagemaker/config/controller/kustomization.yaml
services/sagemaker/config/controller/service.yaml
services/sagemaker/config/crd/bases/sagemaker.services.k8s.aws_trainingjobs.yaml
services/sagemaker/generator.yaml
services/sagemaker/pkg/resource/model/sdk.go
services/sagemaker/pkg/resource/training_job/sdk.go

Two small changes to the SageMaker TrainingJob Controller - 
1. Add Printer Columns for SageMaker TrainingJob and 
2. Remove DebugRuleEvaluation Status Field (for now) since the job completes after trainingjob and the status reflected is not accurate. Needs further testing and changes to the requeue logic before re-adding this field. 

Add Printer Columns for SageMaker TrainingJob and Remove DebugRuleEvaluation Status Field (for now)

---

cmd/ack-generate/command/common.go

Issue N/A
- Remove the code that was used to delete aws-sdk-go repositories cloned using `--depth=1` 
- Reverts commit a0821335d786c43099c4430510d550bca2547e09.

Remove legacy code: reverts commit a0821335d

---

pkg/generate/code/set_resource.go
pkg/generate/crossplane/crossplane.go
templates/crossplane/pkg/controller.go.tpl

Description of changes: `ReadMany` template was using `.Items` subfield for all `ReadMany` outputs but that's not true for all `ReadMany` resources. For example, RDS `DBCluster` has `.DBClusters` in the returned object. ACK already addresses this in set output code but Crossplane does a filtering before that step so we needed to check whether the filtered list still has any items.
Fixes https://github.com/crossplane/provider-aws/issues/492

crossplane: fix read many template

---

pkg/generate/config/resource.go

Issue #, if available: https://github.com/aws/aws-controllers-k8s/pull/640#issuecomment-760543777
- Add clarying comment about shortnames being distinct within a given cluster

Add comment regarding shortname uniqueness

---

Makefile
docs/contents/dev-docs/testing.md

#633 
1. Desired version of controller-gen binary will be automatically generated with 'make build-controller SERVICE=$SERVICE' command 
2. Removed kubernetes-sigs/controller-tools from prerequisites as users might try to install controller-gen manually and run into errors mentioned in #633 . The Makefile change will anyways install the correct version automatically or indicate the user to install the correct one in case of mismatch as below -
$make build-controller SERVICE=$SERVICE
building ack-generate ... ok.
FATAL: Existing version of controller-gen Version: v0.4.1, required version is v0.4.0.
FATAL: Please uninstall controller-gen and install the required version with scripts/install-controller-gen.sh.
By submitting this pull request, I …

automatically generate desired controller-gen binary

---

scripts/kind-build-test.sh
test/release/test-helm.sh

The PRESERVE env var is by default true. So this means that the cluster is not deleted after test execution.
There are a couple of issues observed when this kind cluster is reused for testing - 
1. When "make kind-test SERVICE=$SERVICE" finishes execution for the 1st time for a given service then at the end the following message is generated to reuse the cluster -
To resume test with the same cluster use: "-c <TMP_DIR path>" 
However the script does not take -c as an argument. Infact the script uses env vars  TMP_DIR and AWS_SERVICE_DOCKER_IMG for reusing the cluster.
Note: If env var TMP_DIR is not set or passed then the script errors out as it tries to recreate the cluster.
If AWS_SERVICE_DOCKER_IMG is not set then the script rebuilds the docker image.    
2. Even …

Corrected scripts for cluster reuse

---

pkg/generate/ack/release.go
pkg/generate/templateset/templateset.go

The pkg/generate/ack/release.go file was calling templateset.New() with
the wrong set of copyPaths (it was passing the api copy paths not the
release copy paths). The templateset.Execute() call was also not
properly constructing a full path for copying by prepending the template
base path to the copied file path.
Related to bugs found in #661 

fix release copy file generation

---

pkg/config/config.go
pkg/runtime/tags.go
scripts/kind-build-test.sh
services/elasticache/config/controller/deployment.yaml
templates/config/controller/deployment.yaml.tpl
templates/helm/templates/deployment.yaml
templates/helm/values.yaml.tpl

Issue #532 
- Added `resource-tags` option by referring to `ACK_RESOURCE_TAGS` environment variable. 
- Generated controllers using:
```
SERVICE=elasticache && make build-controller
```

Config option to specify resource tags

---

CONTRIBUTING.md
README.md
docs/README.md
docs/contents/dev-docs/api-inference.md
docs/contents/dev-docs/overview.md
docs/contents/how-it-works.md
docs/contents/index.md
services/README.md

As the repo name has changed this has caused all the Doc URLs to also change. This updates all references in the repo to point to the new URL.
NOTE: The URL referenced in the GitHub repo (on the right) also needs updating by someone with permission to do so.

fix: update all doc URLs to point to new URL

---

scripts/lib/aws.sh

Currently, the kind-test uses the `daws` script to run AWS cli commands. However, it does not respect $AWS_PROFILE, and instead always uses default.
This pull request changes it, such that if $AWS_PROFILE is set, it will be passed as an environment variable to the Docker run.
There is a tiny bit of wonkiness so that it does not pass anything when $AWS_PROFILE is not set - because in testing, I could not get the --profile option (which may never be used in this setting, either way) to override the environment variable even if it's set to empty.

Add support for non-default AWS profile

---

CODEOWNERS

Added a simple codeowners file which - 
- Currently, will notify the owners in case of changes to any of the directories they own
- [TODO] Can be used to gate code merge on a review from a code owner by [enabling this setting on a protected branch](https://github.blog/2017-07-06-introducing-code-owners/#an-extra-layer-of-code-security). 
- Currently, cross org teams cannot be used as codeowners, so until we create teams within this new org, added members individually. 

Add codeowners for the SageMaker E2E test directory

---

Dockerfile.local
Makefile
scripts/build-controller-image.sh
scripts/kind-build-test.sh

During development, workspace directory setup looks like:
Example setup including ElastiCache service controller along with ACK packages:
```
aws-controllers-k8s
├── code-generator
├── community
├── elasticache-controller
└── runtime
```
To build service controller image against local changes in ```runtime``` module, `elasticache-controller/go.mod` file contains:
```
replace github.com/aws-controllers-k8s/runtime => ../runtime
```
However to run local kind tests (using ```SERVICE=elasticache make kind-test``` from `community` directory) , the controller docker image needs to be built by referring to local `runtime` module from the Dockerfile.
Created a ```Dockerfile.localmodules``` file that refers ```runtime``` module during build/
Updated …

Allow reference to local runtime module from service controller go.mod file during kind-test

---

Dockerfile
scripts/build-controller-image.sh
scripts/build-controller-release.sh

After removing the top-level go.mod/sum files, the
`scripts/build-controller-image.sh` and
`scripts/build-controller-release.sh` scripts were broken.
In the case of `build-controller-image.sh`, we needed to always set the
Docker build context to the top-level
`$GOPATH/src/github.com/aws-controllers-k8s` directory and update the
Dockerfile to always copy the go.mod and go.sum files from the service
controller's repository instead of the old go.mod/sum files from the
original monorepo.
In the case of `build-controller-release.sh`, we needed to pass a
`--aws-sdk-go-version` CLI argument to the `ack-generate release`
command line call to force `ack-generate` to not look for a go.mod file
in order to determine the aws-sdk-go version to use in constructing the
SDK helper for the code generator. …

fix up build scripts to deal with deleted go.mod

---

scripts/build-controller-release.sh

Made a typo in the fix for the build-controller-release script.

fix incorrect ack-generate flag

---

scripts/build-controller-release.sh

- `--aws-sdk-go-version` argument value needed to be a valid tag value ('v' prefix)
- Incorrect template directory was referred when
`./scripts/build-controller-release.sh $SERVICE $RELEASE_VERSION;`
is invoked.
Updated `build-controller-release.sh` script.

Fix errors while build controller release

---

docs/contents/dev-docs/release.md

While following the `release.md` steps the `publish-controller-image.sh` script needs to be invoked with `AWS_SERVICE_DOCKER_IMG` environment variable set to expected value. Else, incorrect value (like `public.ecr.aws/aws-controllers-k8s/controller:elasticache-v0.0.2-38-g7e23fa3-dirty`) is used as default.
Note: the tag `v0.0.2` and `38` commits and commit `g7e23fa3` refers to `community` repository and not the expected `elasticache-controller` repository. The `publish-controller-image.sh` needs fix for this default value. 
* Created issue #693 for it.
During release steps, the default behavior is not correct; thus, there is a need to specify `AWS_SERVICE_DOCKER_IMG` environment variable.
* Updated `release.md` file to specify image tag …

Specify image tag during 'Publish the controller images' release step

---

docs/contents/dev-docs/overview.md
docs/contents/dev-docs/setup.md
docs/mkdocs.yml

This change fixes the links to the building controller doc in the
Overview and Setup pages of the dev docs, and adds a nav entry for
that page in the mkdocs config. Previously, these links weren't
resolving as expected on the aws-controllers-k8s.github.io site.
This change has been validated with a local mkdocs preview.

Update links to building controller doc

---

.github/workflows/e2e-test-elasticache.yaml
scripts/kind-build-test.sh

* Add unit test workflow for ElastiCache using the split repositories.
* Added unit test workflow for ElastiCache using the split repositories.

ElastiCache controller e2e test workflow with split repo

---

README.md
docs/contents/releases.md
docs/contents/services.md

Our existing single "release status" was too coarse and was leading to
confusion -- both from customers as well as internal service teams --
about supportability and maintenance policy for controllers in the
different release statuses.
This patch updates our documentation to clarify what we mean by a
"release" and a "version". It also describes two separate concepts:
the **project stage** and the **maintenance phase**.
The controller's "project stage" describes how far along the controller
is towards being released:
`PROPOSED` -> `PLANNED` -> `BUILD` -> `RELEASED`
There's nothing about our support stance or what percentage of an API's
resources need to be implemented or what test coverage is the bar to
reach. Instead, the `RELEASED` project stage is reached when a SemVer Git
tag is …

releases, project stages and maintenance phases

---

test/e2e/common/k8s.py
test/e2e/sagemaker/__init__.py
test/e2e/sagemaker/resources/endpoint_base.yaml
test/e2e/sagemaker/resources/endpoint_config_single_variant.yaml
test/e2e/sagemaker/tests/__init__.py
test/e2e/sagemaker/tests/test_endpoint.py
test/e2e/sagemaker/tests/test_endpoint_config.py
test/e2e/sagemaker/tests/test_model.py
test/e2e/sagemaker/tests/test_processingjob.py
test/e2e/sagemaker/tests/test_trainingjob.py

- Integration tests for endpoint config and endpoint resources in SageMaker
- Endpointconfig: create, delete
- Endpoint: create, read, update, delete
- Enhancements:
- k8s get_resource: it throws an APIException if the resource is not found
- k8s delete: waits for a resource to be removed from the server
- k8s patch resource: can be used for testing update operations
- sagemaker tests: remove sleep for testing delete
- sagemaker model test: add delete test
Using local kind cluster and pytest
I ran black linting tool by mistake on `sagemaker/tests/` directory but didn't want to mix it in this PR. Please bear with some formatting changes in this PR. I will push another PR after this is merged for lining python files
By submitting this pull request, I confirm that my contribution is made …

integ tests: sagemaker endpoint config and endpoint

---

test/e2e/common/k8s.py
test/e2e/elasticache/__init__.py
test/e2e/elasticache/resources/replicationgroup_cmd_fromsnapshot.yaml
test/e2e/elasticache/resources/replicationgroup_input_coverage.yaml
test/e2e/elasticache/service_bootstrap.py
test/e2e/elasticache/service_cleanup.py
test/e2e/elasticache/tests/__init__.py
test/e2e/elasticache/tests/test_replicationgroup.py
test/e2e/elasticache/util.py

Add tests (and associated setup/teardown) to cover most fields in the replication group create input.

Elasticache: setup python test framework, add replication group input coverage tests

---

.github/workflows/e2e-test-elasticache.yaml
scripts/lib/aws/elasticache.sh
test/e2e/elasticache/cache_parameter_group/e2e.sh
test/e2e/elasticache/cache_subnet_group/smoke.sh
test/e2e/elasticache/replication_group/misc.sh
test/e2e/elasticache/replication_group/replication.sh

Similar to #696, but also logging an AWS describe call and k8s object state where applicable (in addition to controller logs), to help us debug issues with our e2e test setup on Github Workflows
Also changing config for github workflow (script is complaining about AWS_PROFILE being unbound)

Elasticache: enhance logging for test assertion failures

---

scripts/build-controller.sh

Issue N/A
Merge `build-controller.sh` and `Makefile` changes from https://github.com/aws-controllers-k8s/code-generator/commit/92458ababbeb0cd0f00b93e149ccc6b4e42f2835:
- Add missing environment variables `AWS_SDK_GO_VERSION` and `TEMPLATES_DIR`  to `build-controller.sh` script
- Add `-tags=codegen` arg to the go install ack-generate command
- Remove `build-ack-generate` step from `build-controller` step

Add missing environment variables to `build-controller.sh`

---

test/e2e/elasticache/resources/snapshot_kms.yaml
test/e2e/elasticache/snapshot/e2e.sh
test/e2e/elasticache/tests/test_snapshot.py
test/e2e/elasticache/util.py

Converted Snapshot test with KMS key from bash to Python. This test was previously failing due to IAM issues (the test IAM role needs a custom KMS policy attached because the AWS-managed `AWSKeyManagementServicePowerUser` policy is not enough). I'll be following this up with some changes to the `elasticache-controller` repo's `config/iam` directory detailing how to set this up.

Elasticache: convert KMS snapshot test to Python

---

.github/workflows/e2e-test-elasticache.yaml
scripts/kind-build-test.sh
test/e2e/run-tests.sh

Description of changes: 
- Add option to skip python tests and execute bash tests instead: the default behavior remains to execute the python tests, but now that can be overridden if `SKIP_PYTHON_TESTS` is set `true`.
- Update usage message
- Remove invocation of python tests from `run-tests.sh` and clean up script
Regarding `run-tests.sh`: I removed the check for an `__init__.py` file since this check already exists in `kind-build-test.sh`; it was pretty confusing that even if `enable_python_tests` was set `false`, `run-tests.sh` would be executed and go on to execute python tests anyway (if they exist for the service). 
In other words, `enable_python_tests="true"` means "run the python tests inside Docker" – there's no change there. However, before, `enable_python_tests="false"` meant …

Add option to skip python tests and execute bash tests instead

---

scripts/build-controller-release.sh
test/e2e/build-run-test-dockerfile.sh
test/e2e/run-tests.sh

The automated Python E2E tests (running within a Docker container) were attempting to create a child container, themselves. I fixed this recursion by setting the `RUN_PYTEST_LOCALLY` flag to `true`.
Also, we cannot `source` `common.sh` inside the testing container, so I have moved this call back into the local bash test conditional body.

Fix automated Docker-Python tests

---

test/e2e/common/k8s.py
test/e2e/elasticache/resources/replicationgroup_authtoken.yaml
test/e2e/elasticache/tests/test_replicationgroup.py

Basic Create/Update Auth token tests.
```
elasticache/tests/test_replicationgroup.py::TestReplicationGroup::test_rg_auth_token 
[gw0] [100%] PASSED elasticache/tests/test_replicationgroup.py::TestReplicationGroup::test_rg_auth_token 
============== 1 passed in 843.54s (0:14:03) =================
```

ElastiCache Auth Token Test

---

test/e2e/rds/__init__.py
test/e2e/rds/bootstrap_resources.py
test/e2e/rds/replacement_values.py
test/e2e/rds/resources/db_subnet_group_2az.yaml
test/e2e/rds/service_bootstrap.py
test/e2e/rds/service_cleanup.py
test/e2e/rds/tests/__init__.py
test/e2e/rds/tests/test_db_subnet_group.py
test/e2e/run-tests.sh

This also includes a quick fix to tests/e2e/run-tests.sh that was
referring to the wrong variable name.
```
[jaypipes@thelio community]$ TEST_HELM_CHARTS=false make kind-test SERVICE=rds AWS_ROLE_ARN=$ROLE_ARN
checking AWS credentials ... ok.
creating kind cluster ack-test-7444685b-c9f2a7d8 ... ok.
<snip>
loading the images into the cluster ... ok.
loading CRD manifests for rds into the cluster ... ok.
loading RBAC manifests for rds into the cluster ... ok.
loading service controller Deployment for rds into the cluster ...ok.
generating AWS temporary credentials and adding to env vars map ... ok.
======================================================================================================
To poke around your test cluster manually:
export …
```

simple smoke test for RDS DB subnet group

---

test/e2e/conftest.py
test/e2e/elasticache/resources/replicationgroup_largecluster.yaml
test/e2e/elasticache/tests/test_replicationgroup_largecluster.py
test/e2e/elasticache/util.py

- large cluster load test
- add support for a `pytest.mark.slow` marker, and skip these tests by default (we don't want tests like this to run with the rest of the tests)

Elasticache: replication group large cluster test and support for skipping slow tests by default

---

test/e2e/applicationautoscaling/__init__.py
test/e2e/applicationautoscaling/bootstrap_resources.py
test/e2e/applicationautoscaling/replacement_values.py
test/e2e/applicationautoscaling/resources/dynamodb_scalabletarget.yaml
test/e2e/applicationautoscaling/resources/dynamodb_scalingpolicy.yaml
test/e2e/applicationautoscaling/service_bootstrap.py
test/e2e/applicationautoscaling/service_cleanup.py
test/e2e/applicationautoscaling/tests/__init__.py
test/e2e/applicationautoscaling/tests/test_scalabletarget.py
test/e2e/applicationautoscaling/tests/test_scalingpolicy.py

- Bootstrap using two DynamoDB tables
- One to be used for testing registration of `ScalableTarget`
- One which is pre-registered as a `ScalableTarget` - for testing `ScalingPolicy`
- Smoke tests using a `WriteCapacityUnits` as the scalable dimension

Integration tests for Application Auto Scaling

---

test/e2e/rds/resources/db_security_group_simple.yaml
test/e2e/rds/tests/test_db_security_group.py

Adds a super simple create, read, and delete test for a DB security
group in the RDS API.
Handling allow and revoke of an EC2 security group or IPRange member of
a DB Security Group will be handled in a followup patch after the
rds-controller's DBSecurityGroup resource manager gets custom code that
handles those attributes.
Issue #237

[rds] add create-delete test for DB security group

---

scripts/build-controller-release.sh
scripts/install-operator-sdk.sh
scripts/olm-build-bundle-image.sh
scripts/olm-create-bundle.sh
scripts/olm-publish-bundle-image.sh

Fixes #705 
This commit adds most of the necessary plumbing for generating OLM artifacts, as well as publishing those artifacts to a container registry. 
This takes advantage of the`ack-generate olm` command and `operator-sdk generate bundle` in order to generate artifacts that should be ready to go into an operator collection like https://github.com/operator-framework/community-operators.
* `install-operator-sdk.sh` - This will install install the Operator SDK binary at the current release version (1.6.1) and is modeled after other similar dependency installation scripts.
* `build-controller-release.sh` - This has been updated to include optional logic to both install operator-sdk and use the `ack-generate olm` command to generate necessary manifest bases to feed a downstream bundle …

Add OLM Bundle Generation Scripts

---

scripts/build-controller-release.sh

Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
**Issue #, if available:**
Unblocks me on the following, but this is not the resolution of that issue.
https://github.com/aws-controllers-k8s/community/issues/744 (specifically: https://github.com/aws-controllers-k8s/community/issues/744#issuecomment-830428118)
**Description of changes:**
This change will update the OLM component of scripts/build-controller-release.sh to explicitly set the path to the generator.yaml. The default value of this option (if unspecified) is to be unset (https://github.com/aws-controllers-k8s/code-generator/blob/main/cmd/ack-generate/command/root.go#L115-L117) which causes the OLM bundle generation logic to incorrectly scaffold things for ignored resources.
By submitting this pull request, I confirm …

Explicitly specify a generator config path for ack-generate olm

---

scripts/install-operator-sdk.sh

Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
**Issue #, if available:**
N/A
**Description of changes:**
This bumps the operator-sdk version to v1.7.1 (from v1.6.1) when it's downloaded using the dependency install helper scripts.
👍

Bump operator-sdk version to v1.7.1

---

scripts/build-controller-release.sh

Part of #744 [discussion](https://github.com/aws-controllers-k8s/community/issues/744#issuecomment-832260936)
Currently the aws-sdk-go version is hard coded in the `scripts/build-controller-release.sh`. This commit adds an envirnoment variable `AWS_SDK_GO_VERSION` to be able to set SDK version used to generate the release files.

Add an environment variable to set aws-sdk-go version in `build-controller-release.sh`

---

scripts/build-controller-release.sh

Issue #, if available: #764
Ensures the `build-controller-release.sh` script also generates the common core CRDs (in `runtime/apis/core/<version>`) into the Helm directory structure.

Generate common CRDs in Helm release

---

scripts/olm-create-bundle.sh

Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
**Issue #, if available:**
N/A
**Description of changes:**
The help text for the `SERVICE_CONTROLLER_CONTAINER_REPOSITORY` variable in the olm-create-bundle.sh script refers to an incorrect default value, which renders as empty.
This replaces that variable reference with the correct default `DEFAULT_SERVICE_CONTROLLER_CONTAINER_REPOSITORY`.
**By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.** 👍

Fix service controller repo referencing an empty default variable

---

scripts/install-kind.sh

Description of changes: The script was only installing kind binary for linux while mac alternative exists. The changes will fetch the correct binary for both darwin/linux.

Added check for macos while installing binary.

---

Dockerfile

Changing proxy.golang.org -> goproxy.io (verified working on vpn as well)
```
curl -sSL https://proxy.golang.org/github.com/aws-controllers-k8s/runtime/@v/v0.1.0.info
curl: (6) Could not resolve host: proxy.golang.org
```
```
➜  ~ curl -sSL https://goproxy.io/github.com/aws-controllers-k8s/runtime/@v/v0.1.0.info
{"Version":"v0.1.0","Time":"2021-04-20T17:23:38Z"}%
```

Changing proxy as goproxy.io is not deny listed as much.

---

Dockerfile

Reverts aws-controllers-k8s/community#771
We need to keep using `proxy.golang.org` (Official Go proxy) for building ACK container images. For contributors having troubles to use `proxy.golang.org` they will have to set a different proxy or no-proxy option locally.
- reverts 3d5b481913808159b0302ed5b80cbec0ff455433

Revert #771 "3d5b481913808159b0302ed5b80cbec0ff455433"

---

.github/workflows/e2e-test-elasticache.yaml
.github/workflows/e2e-test.yaml
Makefile
docs/contents/dev-docs/testing.md
scripts/kind-build-test.sh
scripts/lib/aws.sh

`AWS_ROLE_ARN` conflicts with existing environment variables mounted to containers when assuming a role through IRSA. This makes it impossible to generate temporary credentials within a Prow job that uses IRSA to authenticate the pod.
Modified any references to `AWS_ROLE_ARN` to now be `ACK_ROLE_ARN`

Use ACK_ROLE_ARN in place of AWS_ROLE_ARN

---

scripts/lib/aws.sh

Allow AWSCLI inside Docker to consume the `AWS_WEB_IDENTITY_TOKEN_FILE` passed through as a volume.

Assume `AWS_WEB_IDENTITY_TOKEN_FILE` in AWS Docker

---

scripts/lib/aws.sh

Increase the duration of the temporary credentials used for integration testing from 900 seconds to 3600 seconds (1 hour).

Increase duration of temp creds assume

---

docs/contents/dev-docs/release.md
docs/mkdocs.yml

Updating the docs to mention the stable release process in dev-docs/release.md.
See the final formatted layout here: https://github.com/vijtrip2/aws-controllers-k8s/blob/doc-update/docs/contents/dev-docs/release.md

mention the stable release process in dev-docs/release.md

---

Dockerfile
Dockerfile.local

**Issue #, if available:**
Related to #763, but does not close this issue.
**Description of changes:**
This change adds a new `base_image` argument to all Dockerfiles, and sets the default value of this parameter to the original value of `amazonlinux:2`. This should cause no change for existing build workflows.
According to documentation, this new argument must exist prior to the very first `FROM` in order to be used in a `FROM` action call. https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
This enables developers to build a container from this Dockerfile with an alternate target base image for the final stage.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. 👍 
Signed-off-by: Jose R. …

Parameterize controller build image

---

docs/README.md
docs/contents/snippets/reference.md

Description of changes: Fix the casing for the GoDoc link, so it points to the correct API on the page.
Also updated the README to work with the structure assumed by the configuration file.

Fix GoDoc link in docs

---

scripts/provision-kind-cluster.sh

The K8S_VERSION environment variable is being used to select the Kind node version,
which is currently not working as expected, and the code is modified
to allow the environment variable to properly specify the Kind node version.
Add kind node 1.21 version to choices

fix provision-kind-cluster.sh to use K8S_VERSION

---

docs/scripts/gen_reference.py

Getting `KeyError` when accessing `spec['description']`. This PR returns an empty default description if not spec description is available.

Fix docs description keyerror

---

docs/contents/snippets/reference_overview.md
docs/scripts/gen_reference.py

Makes use of the `metadata.yaml` file in each service repository by changing any reference to the SDK service name to the properly capitalised`short_name`. For instance, `sfn` will now be `Step Functions`, `sagemaker` will be `SageMaker`, etc.

Capitalise service name in documentation menus

---

docs/design/proposals/late-initialization/late-initialization.md

Issue #812 , if available:
* Adding the proposal on how to handle server-side defaults/late-initialization in ACK.
* You can find the rendered proposal document [here](https://github.com/vijtrip2/aws-controllers-k8s/blob/late-initializers/docs/design/proposals/late-initialization/late-initialization.md)

Proposal for handling late-initialization in ACK.

---

README.md
docs/contents/index.md
docs/contents/releases.md
docs/contents/services.md
docs/contents/user-docs/install.md
docs/mkdocs.yml

Updates our documentation in order to have our new ECR Public
repositories exposed in appropriate links.
Removes the "Work in Progress" user documentation navigation and
adds our install, IRSA and Authorization user docs to the navigation
sidebar.
Updates the Services matrix with the most up-to-date links and statuses.
Finally, replaces the wording in the documentation index/homepage about
"Developer Preview" and "Not to use in production" with explanation
about our release process and maintenance phases and links to the
install docs.
Issue #829 
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

update docs for separate ECR repos and releases

---

docs/contents/dev-docs/release.md

Description of changes: Using the `make build-controller` target instead of `build-controller-release.sh` script in the docs to release controller artifacts.

Using the 'make build-controller' target instead of 'build-controller-release.sh' script

---

docs/contents/dev-docs/setup.md

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/925
As a result of changing to ECR public, our base images now compile using Go 1.15. Updating the contributor setup document to reflect this.
We should probably try to upgrade all modules to require something like 1.17 when it's gained more traction.

Update Go version to `1.15`

---

docs/content/docs/community/faq.md
docs/content/docs/tutorials/sagemaker-example.md
docs/content/docs/user-docs/install.md

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/969
Update any reference to Helm in the installation documentation, removing references to the deprecated OCI chart Helm CLI verbs

Update installation documentation for Helm 3.7 OCI

---

docs/content/docs/user-docs/authorization.md
docs/content/docs/user-docs/install.md

* use latest s3-controller release for getting-started guide
* This will encourage keeping the guide up-to-date
* there will be less surprises for beginner users when they move from `getting-started` to using latest controllers for their workload
* this will provide the beginner users most up-to-date behavior of ACK controller runtime.

Keep installation docs up-to-date with latest s3-controller version

---

docs/content/docs/community/overview.md

* addressing comments given on https://github.com/aws-controllers-k8s/community/pull/995 after merging
* cleaning up overview.md from unused links
* Keeping install controller link only in `Next Steps` and removing the `Quick link`

remove redundant links from overview.md

---

docs/content/docs/tutorials/autoscaling-example.md

Small updates to the Application Auto Scaling permissions configuration in the stand-alone tutorial based on updates in the controller ReadMe (https://github.com/aws-controllers-k8s/sagemaker-controller/pull/130/commits/194bee023a1eb4af2af6a5ad175bf26e255df7ef)

Updated Application Auto Scaling pass role policy

---

docs/design/proposals/resource-reference/resource-reference.md

Issue #545 
* Proposal for handling resource relationship in ACK custom resources.
* View the rendered proposal [here](https://github.com/vijtrip2/community/blob/res-rel-proposal/docs/design/proposals/resource-reference/resource-reference.md)

proposal for supporting resource references

---

docs/content/docs/contributor-docs/code-generation.md

The crossplane cmd does not appear to have an "apis" sub-command (anymore?)

Fix example crossplane generation cmd

---

docs/package-lock.json
docs/package.json

* update `markdown-it` version as suggested by dependabot alert https://github.com/aws-controllers-k8s/community/security/dependabot
* run `npm install` to update `package-lock.json` file

fix for dependabot alert of 'markdown-it' library

---

docs/package-lock.json
docs/package.json

* fixing `depandabot` security alert for `nanoid` and `shelljs` libraries
* Updated `package.json` and ran `npm install` to update `package-lock.json`

fix security vulnerability for nanoid and shelljs

---

docs/content/docs/tutorials/rds-example.md

This adds a tutorial for how to deploy the ACK service controller for RDS with examples for deploying PostgreSQL and MariaDB instances.

Add tutorial for ACK service controller for RDS

---

docs/content/docs/tutorials/rds-example.md

This reduces the number of parameters required to deploy a RDS
database when following the RDS tutorial. It also uses the engine
major version number, reducing the need to continuously update the
example when a new minor release of the engine is available.
Additionally, the database username is added to the Secret for
convenience, as credentials are typically loaded in apps in this
manner.
---

Simplify examples in the RDS tutorial

---

docs/content/docs/user-docs/authorization.md
docs/content/docs/user-docs/cross-account-resource-management.md
docs/content/docs/user-docs/install.md

Adds explanation in the authorization.md document about the difference
between Cluster Mode and Namespace Mode when starting an ACK controller
including language that describes the various ClusterRole or Role
permissions required for controllers started in either mode.
Issue: aws-controllers-k8s/community#1173
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

document Cluster Mode vs Namespace Mode RBAC

---

docs/layouts/partials/sidebar/list-card.html
docs/layouts/partials/sidebar/reference-menu-item.html
docs/layouts/partials/sidebar/reference-menu.html
docs/layouts/reference/list.html
docs/layouts/reference/single.html
docs/scripts/gen_reference.py
docs/scripts/templates/resource.jinja2

Updates the API reference generator script to support the APIs defined in the `runtime` repository. Also updates the HTML of the API reference page to place the APIs in their own section at the top under `Common`.

Generate runtime API reference documentation

---

docs/content/docs/tutorials/rds-example.md

This moves the Helm chart installation from v0.0.17 to v0.0.20 to utilize the FieldExport functionality.
I realize that we need a better solution instead of manually bumping each time. Here are two options:
1. Proposed by @RedbackThomson, we apply the `curl` method from a previous examples, i.e.
```diff
diff --git a/docs/content/docs/tutorials/rds-example.md b/docs/content/docs/tutorials/rds-example.md
index cf3e376f..6ddc868e 100644
--- a/docs/content/docs/tutorials/rds-example.md
+++ b/docs/content/docs/tutorials/rds-example.md
@@ -42,13 +42,14 @@ This guide assumes that you have:
You can deploy the ACK service controller for Amazon RDS using the [rds-chart Helm chart](https://gallery.ecr.aws/aws-controllers-k8s/rds-chart). You can download …
```

Bump version in RDS example

---

docs/assets/js/darkmode-init.js
docs/assets/js/darkmode.js
docs/assets/scss/common/_dark.scss
docs/assets/scss/components/_buttons.scss
docs/assets/scss/components/_hint.scss
docs/assets/scss/components/_syntax.scss
docs/assets/scss/layouts/_home.scss
docs/layouts/partials/footer/script-footer.html
docs/layouts/partials/head/script-header.html

If a user had set their dark mode preference to light mode, the website would flash on every page load as it needed to load the dark mode switcher script and then update the CSS. This brief flash becomes very annoying when trying to navigate the website. This pull request adds changes from the latest version of Doks to inline a script which loads the dark mode switcher, so that it's loaded before the page has started rendering. 

Fix docs dark mode flashing

---

docs/content/docs/tutorials/memorydb-example.md

Description of changes: Tutorial MemoryDB Example - Deploy MemoryDB Cluster Using the ACK MemoryDB Controller

Tutorial MemoryDB Example - Deploy MemoryDB Cluster Using the ACK MemoryDB Controller

---

docs/content/docs/user-docs/cleanup.md

When installing the ACK Resource Helm Chart there is an environment variable set as CHART_REF=$SERVICE-chart. This creates the folder under /tmp/chart as $SERVICE-CHART. The path in the commands for deleting the CRDs doesn't exist because of that. 
I've updated the page with the right path.

Updating the path for the Helm Chart

---

docs/assets/scss/common/_dark.scss
docs/assets/scss/common/_global.scss

NA
While working on another PR, I noticed that images were only getting resized in the dark them, moving that formatting to the global css, so images appear the same in all styles. Thanks @RedbackThomson for the CSS help!
Signed-off-by: Adam D. Cornett <adc@redhat.com>

Apply max image width for both light and dark modes

---

docs/content/docs/contributor-docs/testing.md

Renames `ACK_ROLE_ARN` to `ASSUMED_ROLE_ARN` in all documentation

Remove references to `ACK_ROLE_ARN`

---

docs/content/docs/tutorials/rds-example.md

Add tutorial for restore rds snapshot. 
either restore Snapshot to DBCluster or restore DBSnapshot to DBInstance

Add tutorial to restore rds db snapshot to dbinstance/cluster

---

docs/content/docs/user-docs/irsa.md
docs/content/docs/user-docs/openshift.md

N/A
Adding in documentation for OpenShift users to setup IRSA (assuming they have a cluster provisioned properly). The existing IRSA documentation works top down starting from step 2, with the one change that I noted on how to obtain the OIDC_PROVIDER. 
There was also a typo in an existing command where `SERVICE` was not taking the exported value that I also updated.
This should probably be `/hold` until the below has been released and PR's to `operatorhub community` repos have been merged for a few controllers.
- Relates: aws-controllers-k8s/code-generator#353
Signed-off-by: Adam D. Cornett <adc@redhat.com>

updating OpenShift and IRSA docs to explain IRSA support in OpenShift

---

docs/content/docs/tutorials/lambda-oci-example.md

Adding a tutorial for how Lambda OCI Images can be deployed using the ACK controller.

Adding Lambda Tutorial for OCI Images

---

docs/content/docs/user-docs/openshift.md

- Fixes: #1406 
Adding in documentation for users that use OpenShift/OLM on how to install optional CRDs (AdoptedResource/FieldExport) into their clusters before they install any of the controllers.
Signed-off-by: Adam D. Cornett <adc@redhat.com>

updating OpenShift install docs for optional CRDs

---

docs/content/docs/tutorials/ec2-example.md

Modified the Network Topology architecture link in EC2 tutorial, with the initial link could view the diagram only in GitHub page but not in community page.

Network Topology link fix

---

docs/requirements.txt
docs/scripts/gen_services.py
docs/scripts/templates/services.jinja2

Adds a simple summary table to the services listing that shows the count of service controllers in GA and Dev Preview maintenance phase.
Unfortunately I cannot functionally test this code because my IAM user does not have access to read from ECR Public for the ack-infra account any longer...

Add summary table showing services in GA/Preview

---

docs/scripts/gen_services.py

The comparison between maintenance phase "NONE" was incorrect since we were adding backticks around the maintenance phase string.

remove NONE maintenance phase from summary

---

docs/design/proposals/destructive-operations/destructive-operations.md

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/82
Draft proposal for mechanisms to protect users against accidental deletion of ACK and/or AWS resources

Semantics for destructive operations design proposal

---

docs/content/docs/tutorials/autoscaling-example.md

Sagemaker endpoint no longer supports "t2" type instances for autoscaling, an instance of that type is currently being used in [this](https://aws-controllers-k8s.github.io/community/docs/tutorials/autoscaling-example/#deploy-a-sagemaker-endpoint) tutorial. This PR replaces it with a ml.m5.large.

Update Application Autoscaling tutorial instance type

---

docs/scripts/gen_reference.py

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1637
Currently, when the scripts that generate the API reference execute, the docs are generated using the alphabetical order of the controller repositories. This places the `prometheusservice-controller` after the `organizations-controller` in the API reference table of contents. However, when rendering the ToC, they are rendered using their short name. This would require that `AMP` is after `ACM` and before `APIGWv2` in the list. This pull request sorts the list of services by their metadata "short name" before executing their templates and adding the data to the YAML.

Sort table of contents by short name

---

docs/scripts/gen_services.py

API Gateway v2's service full name is AmazonApiGatewayv2. Amazon MQ's service full name is AmazonMQ. Due to an off-by-one index error, these service de-stuttered names were appearing as "piGatewayv2" and "Q". This fixes that off-by-one error.

fix service names beginning with "Amazon"

---

README.md

Remove bit about ACK community meetings being posted to Youtube

---

docs/content/docs/contributor-docs/setup.md

Add note about `Unresolved Type X` errors caused by missing build tags. Discussion (Slack): https://kubernetes.slack.com/archives/C0402D8JJS1/p1675605921217409

docs: Add build tag information

---

docs/content/docs/tutorials/autoscaling-example.md
docs/content/docs/tutorials/sagemaker-example.md

Dynamically retrieve the latest version of the Sagemaker controller instead of hardcoding, script is borrowed from https://aws-controllers-k8s.github.io/community/docs/user-docs/install/.

Update command to retrieve Sagemaker controller version

---

docs/content/docs/user-docs/field-export.md

Replace with `registry.k8s.io`

Correct references to outdated `k8s.gcr.io`

---

docs/content/docs/tutorials/autoscaling-example.md
docs/content/docs/tutorials/sagemaker-example.md

Adds curl as a prerequisite since its used in the tutorials.

Add curl as a prerequisite for Sagemaker tutorials

---

docs/content/docs/community/releases.md
docs/content/docs/contributor-docs/release.md
docs/content/docs/tutorials/apigatewayv2-reference-example.md
docs/content/docs/tutorials/autoscaling-example.md
docs/content/docs/tutorials/emr-on-eks-example.md
docs/content/docs/tutorials/memorydb-example.md
docs/content/docs/tutorials/rds-example.md
docs/content/docs/tutorials/sagemaker-example.md
docs/content/docs/user-docs/ack-tags.md
docs/content/docs/user-docs/install.md

https://github.com/aws-controllers-k8s/community/issues/1715
This pull request removes all references to Helm charts and images prefixed with `v`. Some parts of the release documentation still reference mono-repo style image tags. For those parts, I have partially updated them where applicable, but honestly they need to be entirely rewritten to match the current structure.

Remove references to v prefix in Helm charts

---

docs/content/docs/community/how-it-works.md
docs/content/docs/user-docs/drift-recovery.md

Closes https://github.com/aws-controllers-k8s/community/issues/1810
Adds a new document to the "Getting Started" tab of the documentation which outlines the definition and configuration options for ACK drift remediation. Also adds a link to it from the "How it Works" page.

Add drift remediation configuration document

---

docs/content/docs/tutorials/aurora-serverless-v2.md
docs/content/docs/tutorials/autoscaling-example.md
docs/content/docs/tutorials/ec2-example.md
docs/content/docs/tutorials/emr-on-eks-example.md
docs/content/docs/tutorials/lambda-oci-example.md
docs/content/docs/tutorials/sagemaker-example.md
docs/content/docs/user-docs/install.md

Update the documentation to correctly strip the `v` prefix from all tag names, so that they match the structure of the image tags

Fix the release version script for all tutorials

---

docs/requirements.txt

Similarly to what happened to our e2e prow jobs, doc releases are
failing because they are pointing to an old version of `acktest`
This patch fixes that by pointing to the most recent ack-test commit

Fix `docs-release` prow job

---

docs/content/docs/user-docs/adopted-resource.md

- Update docs to give example for when to use `adoptedresource.spec.aws.nameOrId` vs `adoptedresource.spec.aws.arn`
- Add headers for each section of the spec, so they appear in the sidebar and are linkable

Add extra context to docs, for using name vs ARN in adopted resources

---

docs/scripts/gen_services.py

supports direct assignment with --debug=False or --debug=True, but will also support --debug to set True or --no-debug to set False. Default value if not set is false.
Description of changes: removes default false value and adds builtin argparse.BooleanOptionalAction to the debug flag action.
From https://docs.python.org/dev/library/argparse.html#action : 
> "New in version 3.8.
> 
> You may also specify an arbitrary action by passing an Action subclass or other object that implements the same interface. The BooleanOptionalAction is now available in argparse and adds support for boolean actions such as --foo and --no-foo"

Simpler argument handling for debug flag

---

docs/content/docs/user-docs/openshift.md

NA
With the addition of the new flag `--reconcile-default-max-concurrent-syncs`, the OCP `ConfigMap` instructions need to be updated to include this environment variable.

adding RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS to openshift install docs

---

docs/content/docs/user-docs/field-export.md

Description of changes: Fix typo `resourc` -> `resource`

Fix typo in field-export.md

---

docs/content/docs/user-docs/adopted-resource.md

Update relative path to correctly point to feature gate documentation. Also
improve warning format by converting plain text to warning block.

docs: fix broken link to resource adoption documentation

---

docs/content/docs/user-docs/openshift.md

- Fixes: #2252
Updating the OpenShift install configmap values to include `FEATURE_FLAGS` env.

adding FEATURE_FLAGS to openshift install configmap values

---

docs/content/docs/user-docs/features.md

doc: enhance alpha features doc

---

docs/requirements.txt

Issue #, if available: [2501](https://github.com/aws-controllers-k8s/community/issues/2501)
- Update docs scripts to use ackdiscover version with fixes for discovery of Bedrock Agent

Update ackdiscover version

---

docs/content/docs/user-docs/adopted-resource.md

Fixes #2514 
AdoptedResource aws block expects `nameOrID`. Docs incorrectly mentioned `nameOrId` in one place which was confusing.

doc: fix typo nameOrId to nameOrID

---

docs/content/docs/tutorials/lambda-with-secrets-manager.md
docs/content/docs/tutorials/secrets-manager-example.md

- Add tutorial for creating a secret in AWS Secrets Manager with a reference to a Kubernetes Secret
- Add tutorial for retrieving a secret from AWS Secrets Manager from a Lambda function created by ACK 

Add documentation for using Lambda with Secrets Manager
